### ISSUE TITLE
Feature Request : Retrieving QR-Code-Auth Document

### ISSUE THREAD

**Issue by shreya-mishra** [Real-Dev-Squad/website-backend#1011]
**Description:**
Implement a GET API call to retrieve the QR-code-auth document to retrieveEndpoint: GET /auth/qr-code-auth

**API Request**
GET

**Endpoint**
/auth/qr-code-auth

**Query Parameter**:
`device_id: [Specify the device ID you used for the request]
`
**Expected Response**

```
{
  "message": "Authentication document retrieved successfully.",
  "data": {
    "user_id": "SooJK37gzjIZfFNH0tlL",
    "device_info": "t5k77PHnuDSrgEzvMJAj",
    "device_id": "3ioui23u29sjkdnsjkndsk",
    "authorization_status": "NOT_INIT",
    "access_token": "skljalkjdlksjlaskjskld"
  }
}
```

GET /auth/qr-code-auth?device_id=InvalidUserData

Status: 404 Not Found
Response
```
{
  "message": "No Authentication found."
}
```
GET /auth/qr-code-auth?user_id=GTB4UUtlKwGemRN2lwBp11&mobileId=3ioui23u29sjkdnsjkndsk

Status: 400 Bad Request
Response
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "invalid query parameters passed"
}
```

GET /?device_id=3ioui23u29sjkdnsjkndsk

Status: 500 Internal Server Error
Response 
```
{
  "message": "The server has encountered an unexpected error. Please contact the administrator for more information."
}
```

In case of any doubt let's have a discussion on a call or you can text the Mobile-App-React-Native channel on discord.
You can also check our[ API contract](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/qr-code-auth) in case of error responses.

**Comment by shreya-mishra** [comment]
please mention the ETA of the above ticket

**Comment by isVivek99** [comment]
> please mention the ETA of the above ticket
current ETA would be 4 July

**Comment by Satyam005** [comment]
@shreya-mishra can you reassign this to me
