### ISSUE TITLE
Do not return archived users when `/users` api is hit

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-backend#1039]
Currently, all users are returned when the `/users` API is hit. We should not return archive users when the `/users` API is hit by default. If asked for it we will be returning it

**Comment by khalatevarun** [comment]
can i pick this task @prakashchoudhary07 ?

**Comment by prakashchoudhary07** [comment]
Thanks for taking this up, Assigning it to you

**Comment by khalatevarun** [comment]
@prakashchoudhary07 had a doubt here.
The task is to return /users by filtering out the non-archived users.
If we want to fetch the archived users as well, how should we plan to implement it?

A possible solution I could come up with is to pass a flag in the query param
for eg: `/users?query=filterBy:archivedUsers:true`
This will return only archived users
We already have the implementation to extract values from the query params followed by `filterBy:`

Let me know if I should go ahead with this, or is there any other approach we can use

**Comment by prakashchoudhary07** [comment]
> @prakashchoudhary07 had a doubt here. The task is to return /users by filtering out the non-archived users. If we want to fetch the archived users, how should we plan to implement it?
> 
> A possible solution I could come up with is to pass a flag in the query param for eg: `/users?query=filterBy:archivedUsers=true` This will return only archived users We already have the implementation to extract values from the query params followed by `filterBy:`
> 
> Let me know if I should go ahead with this, or is there any other approach we can use

We should not be returning any archived users by default, since they are inactive in RDS
and if we want archived users, then we can pass archivedUsers = true as query params
