### ISSUE TITLE
Additional environment variables needed

### ISSUE THREAD

**Issue by DashDeipayan** [Real-Dev-Squad/website-backend#1061]
## The feature [create-group-roles](https://github.com/Real-Dev-Squad/website-dashboard/issues/340) and [assign-groups](https://github.com/Real-Dev-Squad/website-dashboard/issues/341) requires the following custom variables:

- Discord base URL of Cloudflare for Athena bot: For making requests, we need the base URL of our Discord bot hosted in Cloudflare workers.
Variable name: `DISCORD_BASE_URL`
Location: `website-backend`

- RSA rdsServerlessPrivateKey: For making requests to the discord-bot server, every request must be authenticated with the same key pair that is used to verify in the discord server. Thus, a new key pair with the name `RDS_SERVERLESS` is necessary for creating new tokens.
Variable names: 
 - `RDS_SERVERLESS_PRIVATE_KEY` for Website backend
 - `RDS_SERVERLESS_PUBLIC_KEY` for Cloudflare workers Discord-slash commands

- rdsServerlessTtl: For expiry of the generated token.
Variable name: `RDS_SERVERLESS_TTL`
Location: `website-backend`

|Environment Variable Name |Repository |
| :----------------------------| :-----------|
|RDS_SERVERLESS_PRIVATE_KEY|WEBSITE BACKEND|
|RDS_SERVERLESS_PUBLIC_KEY|DISCORD SLASH COMMANDS|
|RDS_SERVERLESS_TTL|WEBSITE BACKEND|
|DISCORD_BASE_URL|WEBSITE BACKEND|

### Specifications of the key:
- Must be of size 2048.
- Must start with `-----BEGIN RSA PRIVATE KEY-----`
This requirement is because the package `@tsndr/cloudflare-worker-jwt` package used in the `discord-slash-command` project has this set of requirements to function.

### Updates
- A RSA key is to be generated and its private key named `RDS_SERVERLESS_PRIVATE_KEY` is to be set as an environment variable for `website-backend`.
- Its corresponding public key, ' RDS_SERVERLESS_PUBLIC_KEY`, is to be set as an environment variable for `discord-slash-commands` Cloudflare workers.

```

**Comment by bhtibrewal** [comment]
- Permission Required for https://github.com/Real-Dev-Squad/discord-slash-commands/pull/56:
 GUILD_MEMBERS [Privileged Intent](https://discord.com/developers/docs/topics/gateway#privileged-intents)

**Comment by ankushdharkar** [comment]
@bhtibrewal Thank you **SERVER MEMBERS INTENT** under Privileged Gateway Intents is now enabled for our bots: 

<img width="943" alt="image" src="https://user-images.githubusercontent.com/1935403/236718482-ffba17b1-5ea0-45ba-bd83-f7416c101259.png">

**Comment by bhtibrewal** [comment]
> * Permission Required for [create GET /discord-members API discord-slash-commands#56](https://github.com/Real-Dev-Squad/discord-slash-commands/pull/56):
>   GUILD_MEMBERS [Privileged Intent](https://discord.com/developers/docs/topics/gateway#privileged-intents)
>   In the [Developer Portal](https://discord.com/developers/applications), you can navigate to your app's settings then toggle the privileged intents on the Bots page under the "Privileged Gateway Intents" section.
>   @ankushdharkar

After adding the requested permissions it is required to invite the bot again to the server.
Once you add scopes, you should see a URL that you can copy and paste into a new tab to do that.

![image](https://user-images.githubusercontent.com/42600164/236719128-d0de953b-c4a2-4a78-9cb5-9d7d87e1a1c2.png)

**Comment by ankushdharkar** [comment]
@bhtibrewal Privileged intents are enabled for the bot ✅
@DashDeipayan All 3+1 secrets are set in production environments ✅
