### ISSUE TITLE
Handle Assignee not found in PATCH `/tasks/:id` API

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-backend#1085]
### Bug
Currently, if we send an assignee username in the PATCH `/tasks/:id` API  payload and it doesn't find a user with the user name, it still gives the status 204

### Expectation
if no user is found with the username it should throw an error.

<img width="725" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/42600164/431b33a4-76b6-4d3d-a524-2fe1b51635fc">

**Comment by khushi818** [comment]
Can you assign me this task?

**Comment by khushi818** [comment]
I will send pr by tomorrow
