### ISSUE TITLE
Profile and Discord Image Verification

### ISSUE THREAD

**Issue by DashDeipayan** [Real-Dev-Squad/website-backend#1094]
# Feature to build profile and Discord image verification
This feature will verify if the photo of an individual is the same as the discord's photo.
## Requirements:
- User must be verified by RDS bot!!

## Features:
- The image uploaded by the user will be sent for verification(in a image-verification collection) for the moderators.
  - If there already exists a verification record, the record will be updated with new picture URL and date with approved status as false
  - If no record exists, a new record will be generated.
- Fetching and adding the user's discord profile image in the document that moderators(SUPER USER as of now) will verify.
- An API endpoint to get the user's images(uploaded image and discord profile image) for the moderators to verify.
> Data model
```json
{
    userId: string,
    discordId: string,
    discord: {
        url: string,
        approved: boolean,
        date: Timestamp
    }
    profile: {
        url: string,
        approved: boolean,
        date: Timestamp
    }
}
```

This will require a new API endpoint from RDS bot that will provide the user details.
- https://github.com/Real-Dev-Squad/discord-slash-commands/issues/66

**Comment by DashDeipayan** [comment]
**Will require addition of a new package for image processing [jimp](https://yarnpkg.com/package/jimp)**

### this feature will change the yarn.lock file.

**Comment by ivinayakg** [comment]
```json
{
    userId: string,
    discordId: string,
    discord: {
        url: string,
        approved: boolean,
        date: Timestamp
    }
    profile: {
        url: string,
        approved: boolean,
        date: Timestamp,
        publicId: string
    },
    status: `ACCEPTED` | `PENDING` | `REJECTED`
}
```
updated model for the #1924
