### ISSUE TITLE
Create Composite Index for progresses collection

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1118]
Add the following composite index for progresses collection
1. `taskId` Ascending `type` Ascending `date` Ascending `__name__` Ascending
2. `type` Ascending `userId` Ascending `date` Ascending `__name__` Ascending
3. `taskId` Ascending `date` Ascending `__name__` Ascending
4. `userId` Ascending `date` Ascending `__name__` Ascending

**Comment by prakashchoudhary07** [comment]
Have added these index in staging ✅

**Comment by heyrandhir** [comment]
Thanks @prakashchoudhary07 😊

**Comment by ankushdharkar** [comment]
@heyrandhir Indexes have been created in prod firestore. ✅

**Comment by heyrandhir** [comment]
Thanks @ankushdharkar 🙂
