### ISSUE TITLE
Modify middleware validator  to Filter Users based on their state - ONBOARDING

### ISSUE THREAD

**Issue by shubhamsigdar1** [Real-Dev-Squad/website-backend#1144]
On https://dashboard.realdevsquad.com/users/, we want to filter user whose state is ONBOARDING

## Requirements

- Ensure some testing is done.

## Additional Info:

- Setup Backend First, then fill new-signup form locally(my.realdevsquad.com/new-signup)

**Comment by Aryex82** [comment]
@shubhamsigdar1 I would like to work on this.

**Comment by naivecoder786** [comment]
Hi @shubhamsigdar1 Can I take this task ?
