### ISSUE TITLE
Add Indexes to Firebase Database

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1153]
### Related Issue and PR 

- [x] #1141
- [x] #1142

### Description
We need to add the following indexes to our Firebase database

1. `roles.archived`
2. `username`
3. `__name__`

## Steps to Add Indexes
1. Open the **Firebase console**.
6. Navigate to the **database section**.
7. Click on the **"Indexes"** tab.
8. Click on the **"Add Index"** button.
9. Enter the following details for each index:
    - Collection ID:**users**
    - Field Path: 
           1. `roles.archived` -> Ascending
           2. `username` -> Ascending
           3. `__name__` -> Ascending
    - Query Scope: **Collection**
10. Click on the **"Create Index"** button to add the index.

**Comment by ankushdharkar** [comment]
@sahsisunny Index is being created ✅ 
Thank you for the details.

<img width="924" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/1935403/83cbd139-ca8d-4cbf-bcb3-0e8fa9f4fe18">
