### ISSUE TITLE
Show new users joined in last 31 days in dashboard

### ISSUE THREAD

**Issue by ShekharDhangar** [Real-Dev-Squad/website-backend#1166]
### Issue -
The feature is to show new users who joined RDS more than 31 days and are still in the ONBOARDING state on our dashboard site.
The page will also have the progress/status of the user, what they are working on currently, completed lift simulation, etc.
This will help to track the new users and also help them if they are stuck somewhere for a certain time.

**The approach is:**
1. Get the joining date from the discord API and compare users who joined in the last 31 days and show it on the dashboard site.

**Comment by sahsisunny** [comment]
Completed in #1356
