### ISSUE TITLE
Addition of "email" and "phone number" field to backend.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-backend#117]
Add the `email` and `phone number` fields to the ```User object``` in the backend. Refer the api contract mentioned below for the same.
https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/users

**Comment by ankurnarkhede** [comment]
@Rucha1499 , can we close this if its implemented?

**Comment by swarajpure** [comment]
Implemented in https://github.com/Real-Dev-Squad/website-backend/pull/133/
