### ISSUE TITLE
Add logs of archive details in the archiving process

### ISSUE THREAD

**Issue by gauravsinhaweb** [Real-Dev-Squad/website-backend#1214]
Closes - #1465
Currently, there is a need to enhance the process of assigning users to the `archived` status in the website backend. The current implementation lacks the necessary details, which makes it difficult to track and understand why a developer has been placed in the archived status.

### Solution

To improve this process, we need to introduce the following details while assigning users to the `archived` status:

1. **Reason**: Include a field to capture a brief explanation or reason for putting the developer in the archived status. This will help provide context and assist in future reference or auditing purposes.

2. **Who (ID)**: Add a field to specify the name of the assignee responsible for assigning the developer to the archived status. This will allow for better accountability and facilitate communication between team members.

3. **Superuser ID**: Introduce a field to capture the name of the superuser who is performing the action. This will help identify the authority behind the decision to archive a developer and provide transparency within the system.

**Comment by heyrandhir** [comment]
> ## Ticket Description
> ### Issue
> Currently, there is a need to enhance the process of assigning users to the `archived` status in the website backend. The current implementation lacks the necessary details, which makes it difficult to track and understand why a developer has been placed in the archived status.
> 
> ### Proposed Solution
> To improve this process, we need to introduce the following details while assigning users to the `archived` status:
> 
> 1. **Message**: Include a field to capture a brief explanation or reason for putting the developer in the archived status. This will help provide context and assist in future reference or auditing purposes.
> 2. **Who**: Add a field to specify the name of the assignee responsible for assigning the developer to the archived status. This will allow for better accountability and facilitate communication between team members.
> 3. **Superuser Name**: Introduce a field to capture the name of the superuser who is performing the action. This will help identify the authority behind the decision to archive a developer and provide transparency within the system.
> 
> ETA: will add if the ticket got approved.

We should store the superuser id and the user archived id not the name.
