### ISSUE TITLE
Task percentage must be between 0% and 100%.

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1216]
**Actual behavior:** The Task Percentage field accepts any numerical value and does not limit values to a maximum of 100%. 

**Expected behavior:** The Task Percentage field should only accept values from 0% to 100% and not allow percentages greater than 100% and only allow integer percentages.
  
**Reproduction steps:**
1. Open POSTMAN
2. Hit the PATCH call to `/tasks/:taskId` with the Request body having key percentCompleted with a value > 100 or < 0.

**Comment by khalatevarun** [comment]
@heyrandhir i would like to work on this issue
