### ISSUE TITLE
Completed task shouldn't have the ability to be reopened.

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1218]
**Description**: Currently, it is possible for a task to be marked as "in progress" after it has already been marked as completed. This is an issue as it can lead to inaccurate task tracking and reporting.

**Reproduction steps**:

1. Create a task and mark it as completed.
2. Try to mark the completed task as "in progress."

To fix this issue, we should validate the status of the task before allowing any updates to be made. If a task is marked as completed, it should not be allowed to be updated to "in progress"

**Comment by khalatevarun** [comment]
@heyrandhir can I pick this task if it's not assigned to anyone yet?

**Comment by heyrandhir** [comment]
> @heyrandhir can I pick this task if it's not assigned to anyone yet?

Sure @khalatevarun

**Comment by khalatevarun** [comment]
closing the issue since the new tasks status collection does not include 'COMPLETED'
