### ISSUE TITLE
Create an API to check if the username is already existing

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#123]
When the user signs up using the sign in form, we need to check if the username is already existing as the user types in the username, **in real-time** for better UX

We need an API for it.
It's name can be something like `/users/checkUsername`
Suggestions are open for the name of API

NOTE: It will be the front-end which will keep calling this API every time the username is changed (nothing to do with the backend)

The only job of this API will be to take in a given username, query through the database if it exists and return success/error response correspondingly.

Please comment down if you want this issue assigned to you.

**Comment by saishankarmanugula** [comment]
Can you assign it to me @swarajpure
