### ISSUE TITLE
 Add `CRON_JOB_PUBLIC_KEY` environment variable with RSA 2048-bit key

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-backend#1288]
### Description:
We are enhancing our application's security by implementing a public key-based authentication mechanism for our cron jobs. We must add a new environment variable named `CRON_JOB_PUBLIC_KEY` to our PRODUCTION and staging environments. This variable will store an RSA 2048-bit public key that will be used for authentication purposes.

### Steps to Implement:
1. Generate an RSA 2048-bit key pair (public and private keys). Keep the private key secure and only store the public key.
2. Add the `CRON_JOB_PUBLIC_KEY` environment variable to the configuration of both the PRODUCTION and staging environments.
3. Save the generated RSA 2048-bit public key as the value of the `CRON_JOB_PUBLIC_KEY` environment variable in each environment.

Command:
```bash
ssh-keygen -b 2048 -t rsa 
```
Key Name: CRON_JOB_PUBLIC_KEY

### Additional Information:
- Keep the private key secure. We will use it when we set up the repository for corn jobs.
- Handle the private key securely. Don't store it in version control or share it.

**Comment by prakashchoudhary07** [comment]
Done

**Comment by ankushdharkar** [comment]
Set the API keys from Cloudflare and RSA keys in GitHub secrets and Railway env variables. Thank you for the details.
