### ISSUE TITLE
Create levels of access in the recently added data access layer

### ISSUE THREAD

**Issue by mailmesriza98** [Real-Dev-Squad/website-backend#1314]
Parent issue: 
- https://github.com/Real-Dev-Squad/website-backend/issues/1196

In the current data access layer we are removing all the sensitive informational details like **phone, email, chaincode, tokens.** while fetching users data.
However, going forward we would be providing an option to provide different levels of access in the dataAccess layer so that 
the module utilizing the data access layer can pass on its requirement (level 1 or 2 etc) for the granularity of information needed in the sensitive user data.

The levels will be categorized as below:
- level 0: all user-sensitive data is removed(phone,email,chaincode,tokens)
- level 1:  email is disclosed along with non-sensitive data
- level 2 : phone and email is disclosed along with non-sensitive data
- level 3 : phone, email and tokens are disclosed alongside non-sensitive data

The module using the dataAccess layer can pass on the levels required as arguments depending on the requirements. 
Also a privileged role like superusers can be able to pass on a certain level at a time if required to gather sensitive information.

Please let me know thoughts and comments on this issue.

**Comment by heyrandhir** [comment]
This approach looks good to me, However I have some doubts 

Will we have some restriction on the layered authorized access. Will layer 0 data be accessible to all user or only super user.  How will we be managing access levels authorization. Implementing robust access control mechanisms rules for user privileges will be essential to avoid data breaches and unauthorized access. 

Additionally, providing detailed documentation on access level guidelines and enforcing best practices will help users and developers understand and adhere to the defined data access policies effectively.

**Comment by vikhyat187** [comment]
Hi @mailmesriza98 if you have any rough approach in mind, can you just create a diagram for the approach that you will follow to implement this?

**Comment by vikhyat187** [comment]
I think granular level based permissions should be implemented, as this can help to protect the system, say a malicious actor tries to cause harm to the resources or misuse the data, we can put the restriction on user level, in case of the role based access we will have to create a new role to restrict him / her.

@heyrandhir @prakashchoudhary07 what are your thoughts

**Comment by prakashchoudhary07** [comment]
I think, we should go ahead with role based approach. We are already having role based system in place.

**Comment by heyrandhir** [comment]
> Hi so as per our discussion we will be storing the levels -> roles relation in the data access layer determining which roles is allowed to how much level. So a general user would have level 0, a superuser can have level 1 and level 2 and have level 0 by default, and restricted users would have no access to any information. Instead of creating a new middleware, once the dataAccessLayer is passed on the required level, it will check if the calling user's data roles match upto the level specified and if it is apt, then the required level of data is returned , else a 403 error is returned. Level 0,1,2,3 could be renamed to Public, Internal, Restricted, Confidential for better readability.
> 
> @prakashchoudhary07 , @heyrandhir , @vikhyat187 let me knoe your thoughts on the same.

Yeah this approach sounds good to me.

**Comment by vikhyat187** [comment]
> Hi so as per our discussion we will be storing the levels -> roles relation in the data access layer determining which roles is allowed to how much level.
> So a general user would have level 0, a superuser can have level 1 and level 2 and have level 0 by default, and restricted users would have no access to any information.
> Instead of creating a new middleware, once the dataAccessLayer is passed on the required level, it will check if the calling user's data roles match upto the level specified and if it is apt, then the required level of data is returned , else a 403 error is returned.
> Level 0,1,2,3 could be renamed to Public, Internal, Restricted, Confidential for better readability.
> 
>  @prakashchoudhary07 , @heyrandhir , @vikhyat187 let me knoe your thoughts on the same.

Yeah agreed this sounds good to me
