### ISSUE TITLE
Remove Feature Flag from Tasks Pagination route

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1359]
**Description**
Currently, there is a feature flag controlling the Task Pagination from the`/tasks` route. This feature has undergone extensive testing in both the development and staging environments and is now ready to be released to all users without the need for the feature flag.

**Comment by Amandixit10** [comment]
please assign this task to me.

**Comment by Amandixit10** [comment]
Here is the list of routes following /tasks

1. https://status.realdevsquad.com/tasks
2. https://status.realdevsquad.com/tasks?q=is%3Aassigned
3. https://status.realdevsquad.com/tasks?q=is%3Aavailable
4. https://status.realdevsquad.com/tasks?q=is%3Aneeds-review
5. https://status.realdevsquad.com/tasks?q=is%3Ain-review
6. https://status.realdevsquad.com/tasks?q=is%3Averified
7. https://status.realdevsquad.com/tasks?q=is%3Amerged
8. https://status.realdevsquad.com/tasks?q=is%3Acompleted
