### ISSUE TITLE
Rename authentication cookie for non-production environments

### ISSUE THREAD

**Issue by ankurnarkhede** [Real-Dev-Squad/website-backend#138]
The cookie being used for staging environment is `rds-session`. Currently, the production UI domain is utilising the  API  from staging. This will cause cookie overriding issues when we will also have production API hosted.
We should better rename the **non-production** auth cookies as `rds-session-<NODE_ENV>`

**Comment by sanyogita14** [comment]
Is anyone working on this issue or can I take it up?
