### ISSUE TITLE
The indexes in the cloud firestore for logs of `archived-details` in the archiving process

### ISSUE THREAD

**Issue by gauravsinhaweb** [Real-Dev-Squad/website-backend#1399]
**Linked to issue #1214**

By adding the necessary indexes, we aim to improve the overall performance and response time of fetching `archived-details` logs.

### Description 
- We need to add the following indices to our Firebase database

### Collection Name: `logs`

![Screenshot 2023-08-11 190734](https://github.com/Real-Dev-Squad/website-backend/assets/75125943/adb27038-90df-43da-8638-d94a04868c8c)

## Steps to Add Indices
1. Open the **Firebase console**.
2. Navigate to the **database section**.
3. Click on the **"Indexes"** tab.
4. Click on the **"Add Index"** button.

### Indexes:
GET **`/logs/archived-details`**

[https://console.firebase.google.com/v1/r/project/<PROJECT_NAME>/firestore/indexes?create_composite=Cltwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvZXh0ZW5zaW9uUmVxdWVzdHMvaW5kZXhlcy9fEAEaCgoGdGFza0lkEAEaDQoJdGltZXN0YW1wEAEaDAoIX19uYW1lX18QAQ](https://console.firebase.google.com/v1/r/project/rds-backend-b97d0/firestore/indexes?create_composite=Cllwcm9qZWN0cy9yZHMtYmFja2VuZC1iOTdkMC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbG9ncy9pbmRleGVzL0NJQ0FnT2kzOUlrSxABGggKBHR5cGUQARoNCgl0aW1lc3RhbXAQAhoMCghfX25hbWVfXxAC)

GET **`/logs/archived-details?userId=<ID>`**

[https://console.firebase.google.com/v1/r/project/<PROJECT_NAME>/firestore/indexes?create_composite=Cltwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvZXh0ZW5zaW9uUmVxdWVzdHMvaW5kZXhlcy9fEAEaCgoGdGFza0lkEAEaDQoJdGltZXN0YW1wEAIaDAoIX19uYW1lX18QAg](https://console.firebase.google.com/v1/r/project/rds-backend-b97d0/firestore/indexes?create_composite=Cllwcm9qZWN0cy9yZHMtYmFja2VuZC1iOTdkMC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbG9ncy9pbmRleGVzL0NJQ0FnSmlVc1pJSxABGh4KGmJvZHkuYXJjaGl2ZWRfdXNlci51c2VyX2lkEAEaCAoEdHlwZRABGg0KCXRpbWVzdGFtcBACGgwKCF9fbmFtZV9fEAI)

**Comment by ankushdharkar** [comment]
Both indexes already existed. Nothing has to be done in prod. Marking this as done.

**Comment by gauravsinhaweb** [comment]
### Updated link: 

**Steps to get Project ID**

- Project overview (left panel) > Project settings > Project ID

Index:

- https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=Ck5wcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbG9ncy9pbmRleGVzL18QARoeChpib2R5LmFyY2hpdmVkX3VzZXIudXNlcl9pZBABGggKBHR5cGUQARoNCgl0aW1lc3RhbXAQAhoMCghfX25hbWVfXxAC
