### ISSUE TITLE
Goals Backend Authentication API Creation

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-backend#1432]
# Brief
- ![image](https://github.com/Real-Dev-Squad/website-goals/assets/63191499/ebd5e82d-e96c-44c6-8cb9-0af0af576c2c)
- This is the flow for the authentication of the goals-site.
- A authenticated user will request on the backend (main backend) and from there the backend will call the goals-site backend internally authenticate itself and send user info like `user_id, roles` with a `GOAL_BACKEND_SECRET_KEY` all in the body only and then will return the token for goals-backend `goal-site-token`, which will be used by the user to talk to goal site directly.

## What we need
- We need a simple API, which will call the goal site API with `user_id, roles, GOAL_BACKEND_SECRET_KEY`, and then return the token which can be used to access he goal site backend.

**Comment by pallabez** [comment]
Only personal goal backend is deployed, so we still need to figure out how we can make the connection.

**Comment by ivinayakg** [comment]
# ETA - 28th August 2023

**Comment by pallabez** [comment]
New issue - Tests are failing cause nock is not working

**Comment by skv93-coder** [comment]
Please assign this task to me
