### ISSUE TITLE
Update Query Parameter Format in API Endpoint

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1449]
**Description:**
The current format of the query parameter in our API endpoint `users` is as follows:
`/users?query=filterBy:UNMERGED_PRS+days:<days>`

We would like to update the format to make it more consistent with industry standards and to improve usability. The new format will be:

`/users?q=filterBy:UNMERGED_PRS+days:<days>`

This change will not only make the API endpoint more intuitive for users but also align it with common query parameter naming conventions.

**Acceptance Criteria:**

- [ ] Update the API endpoint `/users` to accept the query parameter in the new format `/users?q=filterBy:UNMERGED_PRS+days:<days>`.
- [ ] Ensure that the old query parameter format `/users?query=filterBy:UNMERGED_PRS+days:<days>` is not deprecated you have to add the new query behind the feature flag.
- [ ] Update relevant documentation and API references to reflect the new query parameter format.
- [ ] Perform thorough testing to ensure that the updated format does not introduce any regressions or issues in functionality.
- [ ] Notify internal teams and external API consumers about this change and provide them with updated documentation.
- [ ] Update any automated tests or scripts that rely on the old query parameter format.

**Comment by skt17** [comment]
ETA 10 September
