### ISSUE TITLE
Error Handling and Multiple Search Terms for /tasks Endpoint

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1456]
**Description:**
We have identified an issue with the "/tasks" endpoint, specifically when users provide an incorrect assignee that does not exist in the database. Additionally, we need to enhance this endpoint to support multiple search terms, such as "assignee," to provide more flexible querying of tasks.

### Issue Details:

**1. Incorrect Assignee Handling:**

- **Route:** `https://api.realdevsquad.com/tasks?status=IN_PROGRESS&dev=true&assignee=sunny-s`
- **Issue:** When the provided assignee does not exist in the database, the endpoint should handle this case gracefully.
- **Desired Behavior:** Instead of returning an error, the endpoint should return a response indicating that no tasks were found for the given assignee, similar to how the "/tasks" route behaves.

**2. Supporting Multiple Assignees:**

- **Route:** `https://api.realdevsquad.com/tasks?status=IN_PROGRESS&dev=true&assignee=sunny-s,john-d`
- **Requirement:** Enhance the "/tasks" endpoint to support multiple assignees in the query parameters.
- **Desired Behavior:** When multiple assignees are provided, return the tasks assigned to any of the specified assignees. Ensure that the endpoint can handle multiple comma-separated assignee values.

### Proposed Solutions:

**1. Incorrect Assignee Handling:**
- Modify the "/tasks" endpoint to check if the provided assignee exists in the database.
- If the assignee exists, return the tasks assigned to that user as usual.
- If the assignee does not exist, return a response stating, "No tasks found for the given assignee."

**2. Supporting Multiple Assignees:**
- Enhance the "/tasks" endpoint to parse and handle multiple assignee values when provided as comma-separated values in the query parameters.
- Return the tasks assigned to any of the specified assignees.

Additionally, please ensure that appropriate error handling is in place to handle any other potential issues that may arise during the execution of this endpoint.

**Comment by ajoykumardas12** [comment]
I will do this task.

**ETA: 14th September**

**Comment by 0xatulpatil** [comment]
Hey is this issue still un-assigned? 
Would love to work on it. 

**ETA:  18th September**

As this is my first issue my ETA may vary.
