### ISSUE TITLE
create group 'group-idle-7d+'

### ISSUE THREAD

**Issue by prjwl16** [Real-Dev-Squad/website-backend#1488]
### Problem
Currently our application lacks an API endpoint which can add group `@gruop-idle-7d+` on users who are idle for more than 7 days.

### Solution:
- To address this issue, i will be adding new API endpoint in `discordActions` that will retrieve all users who are idle and will check for the users who are idle for more than 7 days.
- If there are users who are idle for more than 7 days then the script will add a tag `@group-idle-7d+` on them

**Comment by iamitprakash** [comment]
duplicate issue- https://github.com/Real-Dev-Squad/website-backend/issues/1523
