### ISSUE TITLE
Create the indexes for tasks model

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1525]
**Create the indexes in Firestore:**
We need to add the following indexes to our Firebase database
- [ ] Fields: assignee Ascending, status Ascending, endsOn Descending, `__name__` Descending
- [ ] Fields: tasks Ascending, status Ascending, endsOn Descending, `__name__` Descending
- [ ] Fields: tasks Ascending, assignee Ascending, status Ascending, endsOn Ascending, `__name__` Ascending

<details>
<summary>Steps to Add Indexes</summary>

1. Open the **Firebase console**.
2. Navigate to the **database section**.
3. Click on the **"Indexes"** tab.
4. Click on the **"Add Index"** button.

</details>

## Links for create indexes
- https://console.firebase.google.com/v1/r/project/<name>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC1lZjZlZi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QARoMCghfX25hbWVfXxAB
- https://console.firebase.google.com/v1/r/project/<name>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC1lZjZlZi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QAhoMCghfX25hbWVfXxAC
- https://console.firebase.google.com/v1/r/project/<name>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC1lZjZlZi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCgoGZW5kc09uEAEaDAoIX19uYW1lX18QAQ

**Comment by ankushdharkar** [comment]
Thank you for the links. All created.

**Comment by sahsisunny** [comment]
> * https://console.firebase.google.com/v1/r/project//firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC1lZjZlZi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QAhoMCghfX25hbWVfXxAC

@ankushdharkar this index has not been created yet.
