### ISSUE TITLE
Make `website` field optional from users

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#153]
The [frontend](https://my.realdevsquad.com/signup) says that the `website` is optional but if we send blank in website field, the backend sends that `website` cannot be empty and hence form cannot be submitted

**Comment by ankurnarkhede** [comment]
We shouldn't save empty strings as website value.  This is an issue from the UI. The UI shouldn't be sending empty strings for website value.

**Comment by ankurnarkhede** [comment]
The UI should have the empty string checks and all the validation required before sending the data.
@swarajpure can you confirm this?
We can then close this issue.

**Comment by swarajpure** [comment]
Handling the issue on UI level.
Closing this issue
