### ISSUE TITLE
Send `phone` and `email` only for `users/self` route if query `private` is true

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#155]
Since the signup form is now taking phone number and email address, we should not send them as response for every API. No user should be able to see other user's phone number and email address.

No route other than `GET users/self` should return `phone` and `email` and that too only if query `private` is set to true

**Comment by ankurnarkhede** [comment]
API contract: https://github.com/Real-Dev-Squad/website-api-contracts/pull/23
