### ISSUE TITLE
Remove the POST /users route

### ISSUE THREAD

**Issue by ankurnarkhede** [Real-Dev-Squad/website-backend#161]
Currently, any user can create/update a new user([code](https://github.com/Real-Dev-Squad/website-backend/blob/develop/controllers/usersController.js#L78)). Is this API required, or is it being used anywhere? We can use the `PATCH /users/self` route for updating self user's data.

As per I checked, we are not utilising this route and we do not require this. This route and the corresponding functions should be removed.

cc: @ankushdharkar , @whyDontI

**Comment by correaswebert** [comment]
Could you assign this to me @ankurnarkhede ?

**Comment by swarajpure** [comment]
> 
> 
> Could you assign this to me @ankurnarkhede ?

@correaswebert We already have got a PR for this issue: #172
Let's see if the author (outside the organisation) makes the required changes otherwise we'll let you know if this issue is available
