### ISSUE TITLE
Change the time for standup update timing.

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1632]
currently standup acceptance time is 6 am IST. We need to update it to 12 am IST

**Comment by shubhalgupta** [comment]
@heyrandhir please assign this issue to me!

**Comment by heyrandhir** [comment]
> @heyrandhir please assign this issue to me!

Sorry this is already assigned to me. Missed to update here.

**Comment by heyrandhir** [comment]
As confirmed by @ankushdharkar here https://discord.com/channels/673083527624916993/735598747949465640/1168026715176570930 . We will be sticking with the current time window of 6am to 5.59 am IST.
