### ISSUE TITLE
[Migrate] - JavaScript to TypeScript

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1645]
**Description:**
We need to migrate the existing JavaScript codebase to TypeScript for better type safety and improved maintainability.

**Migration Checklist:**
- [x] #1646
- [x] `constants` : #1643 
- [ ] `controllers`
- [ ] `middlewares`
- [ ] `mockdata`
- [ ] `models`
- [ ] `routes` : #1662
- [ ] `scripts`
- [ ] `services`
- [ ] `test`
- [ ] `utils`

**Comment by Priyanshu085** [comment]
I can do this task. Please, assign it to me.
