### ISSUE TITLE
Add firebase index to Task Requests Collections in PRODUCTION

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/website-backend#1687]
### Description 
- We need to add the following indexes to our Firebase database

## Steps to Add Indices
- ### Manually:
1. Open the **Firebase console**.
2. Navigate to the **database section**.
3. Click on the **"Indexes"** tab.
4. Click on the **"Add Index"** button.

- ### Using Link:
1. Replace the <PROJECT_ID> with the actual production database project Id.
- Status with created ascending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGg0KCWNyZWF0ZWRBdBABGgwKCF9fbmFtZV9fEAE

- Status with created descending
https://console.firebase.google.com/u/0/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGg0KCWNyZWF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

- Status with requestors count descending
https://console.firebase.google.com/u/0/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGg4KCnVzZXJzQ291bnQQAhoMCghfX25hbWVfXxAC

- Status with requestors count ascending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGgoKBnN0YXR1cxABGg4KCnVzZXJzQ291bnQQARoMCghfX25hbWVfXxAB

- Request type with requestors count ascending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RUeXBlEAEaDgoKdXNlcnNDb3VudBABGgwKCF9fbmFtZV9fEAE

- Request type with requestors count descending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RUeXBlEAEaDgoKdXNlcnNDb3VudBACGgwKCF9fbmFtZV9fEAI

- Request type with created ascending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RUeXBlEAEaDQoJY3JlYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

- Request type with created descending
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClZwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza1JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RUeXBlEAEaDQoJY3JlYXRlZEF0EAIaDAoIX19uYW1lX18QAg

**Comment by ankushdharkar** [comment]
✅ All 8 indexes created. Thank you for the details.
