### ISSUE TITLE
Paginate logs API

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-backend#1697]
# Paginate logs API

### Requirement
We have to paginate the logs API so that it should not return all the data at once and return data in a batch.
Problem with logs API not paginated:
- Currently if we fetch logs and if the logs are in bulk it would cost our DB very high amount of reads.
- Rendering big amount of data at once can also affect frontend performance.
- In `live-site` we're polling logs API so we will fetch large amount of logs every `x seconds`, which is not idle.

### API URL 
`{{BASE_URL}}/logs/:type`

> Note: Before paginating the API make sure you check where this API is being used so that the functionality of the other features doesn't get broke. This task also includes scoping out this and changing the frontend code too by mentioning respective PRs, after that only PR for this will be merged.

### Questions you can have in mind
- Is this should be under feature flag?
Yes, it should be under feature dev=true

- What is feature flag?
It's a simple variable which we can use to turn off/on the feature. Currently we use dev=true in URL query.

**Comment by skv93-coder** [comment]
Please assign this to me

**Comment by skv93-coder** [comment]
No longer required.
