### ISSUE TITLE
[Production] Create Index for paginated /tasks

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-backend#1730]
Index for `/tasks` API for filtering properties and ordering fields like updatedAt, endsOn, title, status

##

<img width="422" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/d334ac06-ad94-4ab9-9d45-a37a93689965">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=ClRwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9DSUNBZ0pqRjlvSUsQARoJCgV0aXRsZRABGg0KCXVwZGF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

##

<img width="437" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/e7332a79-7067-4371-bf6e-e8e593da816c">

 https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaDQoJdXBkYXRlZEF0EAIaDAoIX19uYW1lX18QAg
 
 ##
 
<img width="428" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/766763fb-90e3-4ae4-a59c-9f0ac2aa2f36">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaDQoJdXBkYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

##

<img width="675" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/ce9adcb4-aa78-4c04-8595-f4da4b98e3da">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCgoGZW5kc09uEAEaDAoIX19uYW1lX18QAQ

##

<img width="434" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/435ec466-7b16-41ba-ab45-d7f29ac4ae5f">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCQoFdGl0bGUQAhoNCgl1cGRhdGVkQXQQARoMCghfX25hbWVfXxAB

##

##

<img width="444" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/b48110d7-6692-46ca-87dc-ffca30c7d975">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCgoGZW5kc09uEAIaCgoGc3RhdHVzEAIaDAoIX19uYW1lX18QAg

##

<img width="440" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/881ff196-38bf-4bc8-8972-b2179dd56d7d">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoNCgl1cGRhdGVkQXQQAhoMCghfX25hbWVfXxAC

##

<img width="453" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/e9a63896-5b10-45a2-8038-871c8f369fd6">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoNCgl1cGRhdGVkQXQQARoMCghfX25hbWVfXxAB

##

<img width="434" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/ea55da24-bd4f-41e2-9a69-3aee5f5b4f9f">

 https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QARoMCghfX25hbWVfXxAB
 
 ##
 
 
<img width="402" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/3b10f22b-6e6b-43dc-98aa-19f198d0a913">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCQoFdGl0bGUQARoNCgl1cGRhdGVkQXQQAhoMCghfX25hbWVfXxAC

##

<img width="452" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/2bbb9e14-4285-4955-8371-540740859e71">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCQoFdGl0bGUQAhoNCgl1cGRhdGVkQXQQARoMCghfX25hbWVfXxAB

##

<img width="444" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/ba7cc5ab-27fd-4187-a751-012a7cbb30f7">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoJCgV0aXRsZRABGg0KCXVwZGF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

##

<img width="454" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/97230f4d-aef5-401e-bb5e-bc8fa8181015">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoJCgV0aXRsZRABGg0KCXVwZGF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

##

<img width="481" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/42cf053d-befe-4689-9419-f94527a8909a">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoJCgV0aXRsZRACGg0KCXVwZGF0ZWRBdBABGgwKCF9fbmFtZV9fEAE

##

<img width="434" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/7b4a63f1-b94c-4545-80bb-ac334bd64176">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QAhoKCgZzdGF0dXMQAhoMCghfX25hbWVfXxAC

**Comment by prakashchoudhary07** [comment]
Index to be removed from the database:

status ascending endsOn ascending __name__ ascending
status ascending endsOn descending status descending __name__ descending
assignee ascending status ascending endsOn ascending __name__ ascending
assignee ascending status ascending endsOn descending status descending __name__ descending

(TIP: Increase rows per page view to max, then copy the whole string and try to search on the index page, to delete it easily )

**Comment by prakashchoudhary07** [comment]
## Index to be added (NEW)

<img width="490" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/8b743806-bb38-4db8-b34c-a389e07257c6">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCgoGZW5kc09uEAEaDQoJdXBkYXRlZEF0EAIaDAoIX19uYW1lX18QAg

##

<img width="493" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/0b43c520-7489-410e-baf3-c93c0a87b2ee">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCgoGc3RhdHVzEAEaCgoGZW5kc09uEAIaDQoJdXBkYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

##

<img width="523" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/6f240381-480f-4f01-b602-cc95deef4913">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoNCgl1cGRhdGVkQXQQAhoMCghfX25hbWVfXxAC

##

<img width="472" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/eaa2703d-8ca5-4887-bbd9-c349d923a143">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoNCgl1cGRhdGVkQXQQARoMCghfX25hbWVfXxAB

##

<img width="494" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/0b1f2d7f-76fb-447e-9390-059cc6cbf575">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QARoNCgl1cGRhdGVkQXQQAhoMCghfX25hbWVfXxAC

##

<img width="479" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/85a30584-994b-4a15-a5c3-ffcbea8c45c9">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoKCgZlbmRzT24QAhoNCgl1cGRhdGVkQXQQARoMCghfX25hbWVfXxAB

##

<img width="486" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/68cbf13c-480a-4b68-9860-56cced2523b5">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoJCgV0aXRsZRABGg0KCXVwZGF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

##

<img width="501" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/34452139/b0942ba6-3f10-45b6-a88d-9ad70d194d58">

https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Cklwcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoJCgV0aXRsZRACGg0KCXVwZGF0ZWRBdBABGgwKCF9fbmFtZV9fEAE

##

**Comment by prakashchoudhary07** [comment]
Please create these new indexes

ref: https://github.com/Real-Dev-Squad/website-backend/issues/1730#issuecomment-1828601873

**Comment by ankushdharkar** [comment]
Deleted indexes from this comment - https://github.com/Real-Dev-Squad/website-backend/issues/1730#issuecomment-1828549937

Added indexes from here - https://github.com/Real-Dev-Squad/website-backend/issues/1730#issuecomment-1828601873

Thank you for laying out the information nicely! 👍
