### ISSUE TITLE
Error in API Endpoint: Unexpected Server Error when Retrieving User Standup Updates

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-backend#1759]
### Issue Description
The API endpoint "https://api.realdevsquad.com/progresses?userId=jbGcfZLGYjHwxQ1Zh8ZJ" is not working and returns an error message.

### Expected Behavior
The API should return user standup updates for the specified user ID without encountering errors.

### Current Behavior
When trying to access the API, the server returns the following error message: "The server has encountered an unexpected error. Please contact the administrator for more information."

### Screenshots
N/A

### Reproducibility
- [x] This issue is reproducible
- [ ] This issue is not reproducible

### Steps to Reproduce
1. Make a GET request to the API endpoint: "https://api.realdevsquad.com/progresses?userId=jbGcfZLGYjHwxQ1Zh8ZJ"
2. Observe the error message returned by the server.

### Severity/Priority
- [x] Critical
- [ ] High
- [ ] Medium
- [ ] Low

### Additional Information
N/A

### Checklist
- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by astron98** [comment]
@sahsisunny Hi Sunny, is this issue resolved as I'm unable to see any error.
