### ISSUE TITLE
Composite Indexes needed in the Production Environment for `/progresses`

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1768]
### Issue Description

Since a new query parameter, `date`, has been introduced in the `/progresses` route, we must create new composite indexes in the production environments. Please note that some indexes may already exist, but to ensure none are overlooked, I have included them below (the indexes after sl no. 4 might be already existing in our indexes):

| Sl No | Collection ID	 | Fields indexed                                                      |
|-------|----------------|---------------------------------------------------------------------|
| 1     | progresses     | taskId Ascending type Ascending date Descending __name__ Descending |
| 2     | progresses     | 	type Ascending date Ascending __name__ Ascending                   |
| 3     | progresses     | 	taskId Ascending type Ascending date Ascending __name__ Ascending  |
| 4     | progresses     | 	userId Ascending date Ascending __name__ Ascending                 |
| 5     | progresses     | type Ascending date Descending __name__ Descending                  |
| 6     | progresses     | type Ascending userId Ascending date Ascending __name__ Ascending   |
| 7     | progresses     | type Ascending userId Ascending date Descending __name__ Descending |
| 8     | progresses     | 	taskId Ascending date Ascending __name__ Ascending                 |

**Comment by ankushdharkar** [comment]
All indexes created on prod. Please let me know if there's anything missing.

Thank you for adding the info. Next time, would appreciate the links to generate index.
