### ISSUE TITLE
Create Indexes for Missed task updates script PRODUCTION

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/website-backend#1789]
### Description 
- We need to add the following indexes to our Firebase database

### Collection Name: 
- `tasks`
- `progresses`

## Steps to Add Indices
1. Replace the <PROJECT_ID> with the actual staging database project Id.

- [ ] Tasks (collection name: `tasks`)

| status     | assignee     | __name__    |
|------------|--------------|-------------|
| Ascending  | Ascending    | Ascending   |

#### Link:
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=Clpwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9DSUNBZ1BqQzRwRUsQARoKCgZzdGF0dXMQARoMCghhc3NpZ25lZRABGgwKCF9fbmFtZV9fEAE

#### Screenshot
<img width="469" alt="Screenshot 2023-12-15 at 5 11 22 PM" src="https://github.com/Real-Dev-Squad/website-backend/assets/98796547/7777b5b6-1c87-4254-b66f-c03163cbb63f">

--- 

- [ ] Progresses (collection name: `progresses`)

| taskid      | type         | date        | __name__    |
|-------------|--------------|-------------|-------------|
| ascending   | ascending    | ascending   | ascending   |

#### Link
https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClRwcm9qZWN0cy9yZHMtYmFja2VuZC05MjVhOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvcHJvZ3Jlc3Nlcy9pbmRleGVzL18QARoKCgZ0YXNrSWQQARoICgR0eXBlEAEaCAoEZGF0ZRABGgwKCF9fbmFtZV9fEAE

#### Screenshot
<img width="497" alt="Screenshot 2023-12-15 at 5 18 37 PM" src="https://github.com/Real-Dev-Squad/website-backend/assets/98796547/8b328f65-c816-4323-ab34-7227c7a3464e">

**Comment by ankushdharkar** [comment]
1 index created, and 1 already existed. ✅
