### ISSUE TITLE
(Production) Create index for Application query 

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-backend#1837]
https://console.firebase.google.com/v1/r/project/rds-test-playground/firestore/indexes?create_composite=Ck5wcm9qZWN0cy91c2Vycy1kNzAxOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvYXBwbGljYW50cy9pbmRleGVzL18QARoKCgZzdGF0dXMQARoKCgZ1c2VySWQQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC

**Comment by ankushdharkar** [comment]
Created in prod. Thank you for the link. ✅
