### ISSUE TITLE
Cookie in development doesn't need to be `secure` (HTTPS)

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#186]
Current the cookie which is being set on development mode is `secure` which makes it available only to `https` whereas `localhost` runs on `http`, so we are unable to see the cookie in browser.

**Comment by ankurnarkhede** [comment]
@swarajpure , secure cookies does not affect any flow in development mode.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies
Can we close this?
