### ISSUE TITLE
[STAGING] - Add indexes to Firebase for /requests API

### ISSUE THREAD

**Issue by Shaily20** [Real-Dev-Squad/website-backend#1932]
##  /requests?dev=true&requestedBy=USERNAME

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaDQoJY3JlYXRlZEF0EAIaDAoIX19uYW1lX18QAg

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaDQoJY3JlYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

## /requests?dev=true&requestedBy=USERNAME&state=STATE

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCQoFc3RhdGUQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCQoFc3RhdGUQARoNCgljcmVhdGVkQXQQARoMCghfX25hbWVfXxAB

## /requests?dev=true&requestedBy=sunny&state=APPROVED&type=OOO

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCQoFc3RhdGUQARoICgR0eXBlEAEaDQoJY3JlYXRlZEF0EAIaDAoIX19uYW1lX18QAg

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCQoFc3RhdGUQARoICgR0eXBlEAEaDQoJY3JlYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

## /requests?dev=true&state=APPROVED&type=OOO

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGgkKBXN0YXRlEAEaCAoEdHlwZRABGg0KCWNyZWF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGgkKBXN0YXRlEAEaCAoEdHlwZRABGg0KCWNyZWF0ZWRBdBABGgwKCF9fbmFtZV9fEAE

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Clhwcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvQ0lDQWdQaWdsNHNLEAEaCQoFc3RhdGUQARoICgR0eXBlEAEaDQoJY3JlYXRlZEF0EAEaDAoIX19uYW1lX18QAQ

## /requests?dev=true&requestedBy=sunny&type=OOO

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCAoEdHlwZRABGg0KCWNyZWF0ZWRBdBACGgwKCF9fbmFtZV9fEAI

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGg8KC3JlcXVlc3RlZEJ5EAEaCAoEdHlwZRABGg0KCWNyZWF0ZWRBdBABGgwKCF9fbmFtZV9fEAE

**Comment by prakashchoudhary07** [comment]
These index are already created in staging ✅

**Comment by sahsisunny** [comment]
## /requests?type=OOO&dev=true

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGggKBHR5cGUQARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC

URL - https://console.firebase.google.com/v1/r/project/rds-backendd/firestore/indexes?create_composite=Ck1wcm9qZWN0cy9yZHMtYmFja2VuZGQvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3JlcXVlc3RzL2luZGV4ZXMvXxABGggKBHR5cGUQARoNCgljcmVhdGVkQXQQARoMCghfX25hbWVfXxAB

**Comment by prakashchoudhary07** [comment]
These indexes are already created in staging ✅
