### ISSUE TITLE
[STAGING] - Add indexes to Firebase for /logs API

### ISSUE THREAD

**Issue by palakgupta2712** [Real-Dev-Squad/website-backend#1979]
## /logs?dev=true&type=TYPE

![image](https://github.com/Real-Dev-Squad/website-backend/assets/61227144/00e0ab0e-9cd2-4638-bade-2088b3f634cb)

https://console.firebase.google.com/v1/r/project/realdevsquad-10012/firestore/indexes?create_composite=Cllwcm9qZWN0cy9yZHMtYmFja2VuZC0xNzY2Mi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbG9ncy9pbmRleGVzL0NJQ0FnSmo3ejRFSxABGggKBHR5cGUQARoNCgl0aW1lc3RhbXAQAhoMCghfX25hbWVfXxAC

<img width="428" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/61227144/0b0d1463-a11f-45b4-aa69-41cec0cd8925">

https://console.firebase.google.com/v1/r/project/realdevsquad-10012/firestore/indexes?create_composite=Ck5wcm9qZWN0cy9yZHMtYmFja2VuZC0xNzY2Mi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbG9ncy9pbmRleGVzL18QARoICgR0eXBlEAEaDQoJdGltZXN0YW1wEAEaDAoIX19uYW1lX18QAQ

**Comment by prakashchoudhary07** [comment]
Thanks for providing the info, have created the indexes
