### ISSUE TITLE
Save `userId` in database for `/tasks` APIs

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#199]
According to the API contracts of `tasks`, we should be saving `userId` in `participants` array and `ownerId` field of task object, but right now our model functions are saving `username` in the `participants` array and `username` in `ownerId` field.

Our frontend should we sending and getting `username` only (instead of `userId`, wherever it is used)
Our controller and model functions will have to modified in such a way that they take `username` and save corresponding `userId` (in the participants array and ownerId field) in the database using the `fetchUser` function
Now our db has got `userId`s in these two fields
Now when we fetch the tasks data, we should be converting the `userId`s back to username in the server and send that in the response.

**Comment by ankurnarkhede** [comment]
Resolved with https://github.com/Real-Dev-Squad/website-backend/pull/230
