### ISSUE TITLE
[STAGING] Need to create composite query(s) for staging

### ISSUE THREAD

**Issue by ashifkhn** [Real-Dev-Squad/website-backend#1999]
### Issue Description

Need composite queries for first, last and username to search users from these.
In our search feature, you can now find people by their first name, last name, or username. So, if you're looking for someone, you can type in any of these details, and the search will show you who matches. To achieve this, we need 3 composite queries in staging for 3 indexes i,e firstname,lastname and username.

URLS:

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Clpwcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9DSUNBZ05pNDdvTUsQARoSCg5yb2xlcy5hcmNoaXZlZBABGgwKCHVzZXJuYW1lEAEaDAoIX19uYW1lX18QAQ

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoOCgpmaXJzdF9uYW1lEAEaDAoIX19uYW1lX18QAQ

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoNCglsYXN0X25hbWUQARoMCghfX25hbWVfXxAB

IMAGE:

<img width="956" alt="Screenshot 2024-04-04 at 20 43 51" src="https://github.com/Real-Dev-Squad/website-backend/assets/54736284/8afa1ae2-e782-40bf-bac7-4e5987762752">

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by prakashchoudhary07** [comment]
Done created the above mentioned indexes, Thanks for the details
