### ISSUE TITLE
[PRODUCTION] Need to create composite query(s) for prod

### ISSUE THREAD

**Issue by ashifkhn** [Real-Dev-Squad/website-backend#2000]
Issue Description
Need composite queries for first, last and username to search users from these.
In our search feature, you can now find people by their first name, last name, or username. So, if you're looking for someone, you can type in any of these details, and the search will show you who matches. To achieve this, we need 3 composite queries in staging for 3 indexes i,e firstname,lastname and username.

URLS:

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Clpwcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9DSUNBZ05pNDdvTUsQARoSCg5yb2xlcy5hcmNoaXZlZBABGgwKCHVzZXJuYW1lEAEaDAoIX19uYW1lX18QAQ

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoOCgpmaXJzdF9uYW1lEAEaDAoIX19uYW1lX18QAQ

https://console.firebase.google.com/v1/r/project/rds-backend-17904/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0xNzkwNC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoNCglsYXN0X25hbWUQARoMCghfX25hbWVfXxAB

**Comment by ankushdharkar** [comment]
Created the indexes. Thank you.
