### ISSUE TITLE
Create composite indexes in production DB 

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-backend#2002]
### Issue Description
We need two composite indexes for the orphan tasks filtration feature 
- https://github.com/Real-Dev-Squad/todo-action-items/issues/215
1. https://console.firebase.google.com/v1/r/project/<RDS_FIRESTORE_ID>/firestore/indexes?create_composite=Clpwcm9qZWN0cy9yZHMtYmFja2VuZC0yZWY0NS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9DSUNBZ05pYXY0QUsQARoUChByb2xlcy5pbl9kaXNjb3JkEAEaDgoKdXBkYXRlZF9hdBABGgwKCF9fbmFtZV9fEAE

2. https://console.firebase.google.com/v1/r/project/<RDS_FIRESTORE_ID>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0yZWY0NS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDgoKYXNzaWduZWVJZBABGgoKBnN0YXR1cxABGgwKCF9fbmFtZV9fEAE

### Screenshots
![image](https://github.com/Real-Dev-Squad/website-backend/assets/55375534/b5603905-c156-4bf7-80c4-7099d46b5522)

**Comment by ankushdharkar** [comment]
Indexes have been created in prod.

**Comment by ankushdharkar** [comment]
Created the indexes in prod. Thank you for the details!
