### ISSUE TITLE
Create composite index in prod DB for orphan task filtration feature

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-backend#2021]
### Issue Description
We need a composite index for the orphan tasks filtration feature (re-implementation) 
#2005 

1. https://console.firebase.google.com/v1/r/project/rds-backend-2ef45/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0yZWY0NS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDAoIYXNzaWduZWUQARoKCgZzdGF0dXMQARoMCghfX25hbWVfXxAB

### Screenshots
<img width="961" alt="image" src="https://github.com/Real-Dev-Squad/website-backend/assets/55375534/2770f816-7277-46c6-901e-2cb0b50b8754">

**Comment by ankushdharkar** [comment]
Thank you for the information. Created the index in prod db. ✅ 

![image](https://github.com/Real-Dev-Squad/website-backend/assets/1935403/2b7a2f67-e219-46f1-a3c3-2e4fcfdb68ee)
