### ISSUE TITLE
API Endpoint /applications?userId=<userID> Should Return Applications Sorted by createdAt Field in Descending Order

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-backend#2093]
### Issue Description
When fetching user applications using the endpoint ```/applications?userId=<userID>``` , the returned array of objects is not ordered. This can result in older applications appearing before newer ones, which is not the expected behavior so return only the latest application in an array.

### Expected Behavior
The API should return an array of single application object which is the latest one. 

### Current Behavior
The API currently returns an unordered array of application objects, making it difficult to view the most recent applications first.

### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Steps to Reproduce
1. Fetch user applications using the endpoint /applications?userId=<userID>
2. Observe that the returned array of objects is not sorted by the createdAt field.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information
To resolve this issue, update the query in the getUserApplications function inside the application model file to include sorting by the createdAt field in descending order by this you will get the latest createdAt time and return that application. The query should look like:
```dbQuery = dbQuery.orderBy("createdAt", "desc");```

here is staging API  where you can see user application for this to view you need to be super user on staging 
check this out how you do this: https://discord.com/channels/673083527624916993/729399523268624405/1135665281155477704
**API** -  https://staging-api.realdevsquad.com/applications?userId=8zJoM4Z8UhcDclALDq9D

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by chandankumarm55** [comment]
Can work on this ??
