### ISSUE TITLE
Lint failing

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#213]
Since we updated the packages last week, `standard` was removed thinking we don't need it anymore, but now the lint is not working:
![image](https://user-images.githubusercontent.com/56217868/109603836-73776b80-7b48-11eb-977a-f5e54e551465.png)

**Comment by ankurnarkhede** [comment]
@swarajpure , where does it say that the library `standard` is required for eslint?
We have added eslint-config-standard and it should work fine.
`standard` is the standalone library for enforcing standard js rules.

**Comment by ankurnarkhede** [comment]
If it was so, the CI would be failing!
