### ISSUE TITLE
Fix user utils file to use data access layer

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-backend#2147]
### Issue Description
In the user utils file, we need to refactor some functions to use the data access layer to avoid circular dependency and other issue

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by pankajjs** [comment]
Hi @vinit717
