### ISSUE TITLE
PATCH method not working on production

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#215]
![image](https://user-images.githubusercontent.com/56217868/109604503-a3733e80-7b49-11eb-9c56-4a5fcd49ea30.png)

It turns out that we need to configure `cors` to allow certain HTTP methods. Documentation: https://expressjs.com/en/resources/middleware/cors.html

**Comment by ankurnarkhede** [comment]
Not reprodicible.
