### ISSUE TITLE
Paginate self Task Api 

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-backend#2180]
### Issue Description
Currently user self task API is not paginated we need to paginate this API and also change the frontend code for this
### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by pradnyesh45** [comment]
Hi @vinit717 , I would like to work on this task.
Currently I am not added to any discord server.
I think the issue is still in process of requirement gathering but I would like to work on this task

**Comment by pankajjs** [comment]
Hi @vinit717 could you assign me this issue?.

**Comment by vinit717** [comment]
Closing this issue as we are going to deprecate/self API
