### ISSUE TITLE
Indexes needed for ProfileDiffs API

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#2189]
### Issue Description

We must create the following Firestore indexes for the profileDiffs collection. These indexes are required to handle queries involving sorting by approval, timestamp, and __name__.

Indexes to be Created:
Index 1:
```
Collection: profileDiffs
Fields:
approval: Ascending
timestamp: Descending
__name__: Descending
```

Index 2:
```
Collection: profileDiffs
Fields:
approval: Ascending
timestamp: Ascending
__name__: Ascending
```

**Comment by ankushdharkar** [comment]
@lakshayman Both indexes have been created. Thank you for the details

<img width="912" alt="image" src="https://github.com/user-attachments/assets/5b929bc4-2244-40c5-aa70-9e8468c04826">
