### ISSUE TITLE
Allow Users to Edit Extension Requests Before Approval

### ISSUE THREAD

**Issue by ahsrah7** [Real-Dev-Squad/website-backend#2195]
### Issue Description

- Currently, once a user raises an extension request, they are unable to edit it, regardless of its status. This issue creates problems when users need to update or correct information before it is  approved.
### Expected Behavior

- Users should be able to edit extension requests if they have not yet been approved.
- Once an extension request is approved, it should become locked for editing.
### Current Behavior

- Users are unable to modify their request details, even if the request has not yet been approved.
### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Raise an extension request as a user.
2. Try to edit the request before it is approved.
3. Observe that editing is allowed on UI but once save is hit the content is still not updated even though the request is still pending approval.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by Mangesh1511** [comment]
if extension requests are made by the logged in user, for the user can we store the extension requests by the user as pending extension requests , and user can edit the pending extension requests and once approved we will update the extension requests.
But I didn't got what are the extension request you are referring to , I assumed this is any feature of the website(actually new, so didn't saw the actual feature), and just proposed a solution,
