### ISSUE TITLE
[Staging] Create composite indexes for departed users 

### ISSUE THREAD

**Issue by VinuB-Dev** [Real-Dev-Squad/website-backend#2277]
### Issue Description
To enable the proper execution of the departed users and orphaned tasks APIs, composite indexes must be added in Firebase. The relevant links are provided below for reference:

`https://console.firebase.google.com/v1/r/project/<project-id>/firestore/indexes?create_composite=Clpwcm9qZWN0cy9yZHMtYmFja2VuZC0yYzMwZC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9DSUNBZ0ppbTE0QUsQARoSCg5yb2xlcy5hcmNoaXZlZBABGhQKEHJvbGVzLmluX2Rpc2NvcmQQARoMCgh1c2VybmFtZRABGgwKCF9fbmFtZV9fEAE`

`https://console.firebase.google.com/v1/r/project/<project-id>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0yYzMwZC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoUChByb2xlcy5pbl9kaXNjb3JkEAEaFgoSdXNlcm5hbWVfbG93ZXJjYXNlEAEaDAoIX19uYW1lX18QAQ`

`https://console.firebase.google.com/v1/r/project/<project-id>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0yYzMwZC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoUChByb2xlcy5pbl9kaXNjb3JkEAEaGAoUZmlyc3RfbmFtZV9sb3dlcmNhc2UQARoMCghfX25hbWVfXxAB`

`https://console.firebase.google.com/v1/r/project/<project-id>/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9yZHMtYmFja2VuZC0yYzMwZC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdXNlcnMvaW5kZXhlcy9fEAEaEgoOcm9sZXMuYXJjaGl2ZWQQARoUChByb2xlcy5pbl9kaXNjb3JkEAEaFwoTbGFzdF9uYW1lX2xvd2VyY2FzZRABGgwKCF9fbmFtZV9fEAE`

### Expected Behavior
The departed users api must work as expected without any issues related to composite index creation in firebase.

### Current Behavior
The departed users api (`users?departed=true&dev=true`) is failing with 500 status.

### Screenshots
![Screenshot 2024-12-01 at 12 20 06 AM](https://github.com/user-attachments/assets/2a57bde0-05c7-4480-b41a-fb09381db584)

### Steps to follow for each of the above links:  
1. Replace `<project-id>` in the link with the **staging project ID**.  
2. Open the modified link in your browser.  
3. Review the composite index details displayed on the Firebase Console.  
4. Click **Save** to add the composite index.  
5. Wait for the index to finish building in the **Composite Indexes** section of Firestore.

**Comment by prakashchoudhary07** [comment]
This is complete, closing it
