### ISSUE TITLE
Add Google OAuth Credentials in config

### ISSUE THREAD

**Issue by listiclehub1** [Real-Dev-Squad/website-backend#2314]
Date: 25/12/2024

Developer Name: Utkarsh Bansal

## Go to Google Cloud Console:
https://console.cloud.google.com/auth/

## Create a New Project or Select exisiting:

Click the dropdown at the top of the page to view your projects.
Click New Project or Select existing Project.

If Google auth platform not configured yet this screen will be shown:

<img width="1436" alt="Screenshot 2024-12-10 at 9 22 28 PM" src="https://github.com/user-attachments/assets/c9ac7451-2897-4a84-84ce-31630197d9fe" />

## If not configured
<details>
<summary>We have to create Configuration</summary>
<img width="1436" alt="Screenshot 2024-12-10 at 9 23 02 PM" src="https://github.com/user-attachments/assets/21c5237b-c455-4900-b3f2-87788f09b7f3" />
<img width="1436" alt="Screenshot 2024-12-10 at 9 23 29 PM" src="https://github.com/user-attachments/assets/4bec7f21-ca35-492a-9d09-f1acfd69aba8" />
<img width="1436" alt="Screenshot 2024-12-10 at 9 23 40 PM" src="https://github.com/user-attachments/assets/7f97a818-e365-428c-805b-e5d8c530cc46" />
<img width="1436" alt="Screenshot 2024-12-10 at 9 23 58 PM" src="https://github.com/user-attachments/assets/d3c57667-c31d-4b59-9caa-19e77bf4987e" />
<img width="1436" alt="Screenshot 2024-12-10 at 9 24 18 PM" src="https://github.com/user-attachments/assets/c6edd819-f1e1-41ef-9736-5e398115f247" />
</details>

#### Click on Create OAuth Client.
<img width="1436" alt="Screenshot 2024-12-10 at 9 24 36 PM" src="https://github.com/user-attachments/assets/5444d00f-c738-4be6-845e-75e510094d05" />

## Fill these details.

- Select `Web Application`
- Add name `Real Dev Squad`
- Add Authorised JavaScript origins `https://realdevsquad.com`
- Add Authorised redirect URIs (This is most important):
 `http://<env url>/auth/google/callback`
 If Env is staging add `https://staging-api.realdevsquad.com/auth/google/callback`
 If Env is Prod add `https://api.realdevsquad.com/auth/google/callback`

<img width="762" alt="Screenshot 2024-12-10 at 9 49 20 PM" src="https://github.com/user-attachments/assets/90acc94f-fbc4-4313-b3b9-af147295b609" />

## Adding to Env

Copy the Client Id and Client secret and add to Env.
- [ ] GOOGLE_CLIENT_ID
- [ ] GOOGLE_CLIENT_SECRET
```javascript
googleOauth: {
    clientId: "GOOGLE_CLIENT_ID",
    clientSecret: "GOOGLE_CLIENT_SECRET",
}

**Comment by Stranger-One** [comment]
I have completed this.

**Comment by listiclehub1** [comment]
> I have completed this. but GitHub don't allow me to push my changes with kyes, so what I do

@Stranger-One Thank you for your effort in creating this pull request to address the issue. However, this particular issue was specifically intended for project maintainers for configuring Google OAuth keys for the staging environment.

To ensure the security, I kindly ask you to:

- Close this pull request immediately.
- Remove any sensitive keys (e.g., Google OAuth credentials) that may have been added or exposed in this PR.

**Comment by prakashchoudhary07** [comment]
Thanks for the detailed information. Have added the keys

<img width="683" alt="image" src="https://github.com/user-attachments/assets/3c1193f9-419d-4c99-9efb-956675fdd550" />

**Comment by Stranger-One** [comment]
Yes, I added the keys in staging. That was my fault, I shouldn't have done
it.

I have closed the pull request because that was only for their maintainers
i think as i received an email.
