### ISSUE TITLE
Create Indexes for itemTags [Staging]

### ISSUE THREAD

**Issue by vikasosmium** [Real-Dev-Squad/website-backend#2321]
**Change the project ID ** 

- https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/indexes?create_composite=ClJwcm9qZWN0cy9yZHMtYmFja2VuZC04NjliOS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvaXRlbVRhZ3MvaW5kZXhlcy9fEAEaDAoIaXRlbVR5cGUQARoOCgpsZXZlbFZhbHVlEAEaDAoIX19uYW1lX18QAQ

- https://console.firebase.google.com/v1/r/project/<PROJECT_ID>/firestore/databases/-default-/indexes?create_composite=ClJwcm9qZWN0cy9yZHMtYmFja2VuZC04NjliOS9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvaXRlbVRhZ3MvaW5kZXhlcy9fEAEaDAoIaXRlbVR5cGUQARoLCgd0YWdOYW1lEAEaDgoKbGV2ZWxWYWx1ZRABGgwKCF9fbmFtZV9fEAE

**Comment by prakashchoudhary07** [comment]
@vikasosmium Thanks for the info, done with the 

<img width="702" alt="image" src="https://github.com/user-attachments/assets/4b857cd2-aec3-4f1d-8b75-83e760321da3" />

<img width="683" alt="image" src="https://github.com/user-attachments/assets/ec409034-39ce-4bcd-bd73-daccdd4b515e" />
