### ISSUE TITLE
Axios not currently needed

### ISSUE THREAD

**Issue by correaswebert** [Real-Dev-Squad/website-backend#245]
As per our current usage, we don't need axios. This would reduce our dependencies too.
Currently, axios is wrapped around a custom fetch in the utils directory, which is being used instead of the built-in fetch.

1. Why are we wrapping axios in fetch and not using it as is?
2. Why are we creating our wrapper around axios instead of the built-in fetch?
3. Why are we creating a wrapper at all, and not using the built-in fetch (given our current use case)?

**Comment by ankurnarkhede** [comment]
@swarajpure

**Comment by swarajpure** [comment]
1. Reason: https://github.com/Real-Dev-Squad/website-backend/issues/84
2. and 3.: Drawbacks of `fetch`: doesn't support timeout, refer: https://github.com/Real-Dev-Squad/website-backend/pull/85#discussion_r528609050

**Comment by swarajpure** [comment]
1. Reason: https://github.com/Real-Dev-Squad/website-backend/issues/84
2. and 3.: `fetch` is not available in node
I was using `node-fetch`, but then @ankurnarkhede pointed out this thing: https://github.com/Real-Dev-Squad/website-backend/pull/85#discussion_r528609050
Hence going with `axios`

**Comment by prakashchoudhary07** [comment]
Closing this as its issues has been resolved
