### ISSUE TITLE
Remove suffix `controller` from controller files

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#280]
The `...Controller` in each filename inside a `controllers` folder is unnecessary redundant context. Let's remove it please

![image](https://user-images.githubusercontent.com/1935403/111886110-06a60300-8989-11eb-8686-482ea0237070.png)

**Comment by K-ash-ish** [comment]
Hey can i do this.

**Comment by ankushdharkar** [comment]
@K-ash-ish I see you already did the changes in #287. Thank you for being proactive!
