### ISSUE TITLE
Tests for /wallet

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#283]
- [ ] User can GET their own wallet
- [ ] User cannot GET someone else's wallet if not authorized
- [ ] If No wallet is found, an empty wallet is created for the user and 1000 dineros is added
- [ ] Authorized user can GET wallet by username

**Comment by sebuelias** [comment]
Can I take this up?

**Comment by sebuelias** [comment]
Hi @ankushdharkar sorry about the delay.
About this issue, I was not able to find the API contract for the wallet, so what are the expected response/errors?
For the 3rd point, we by default create a wallet when adding a new user #285 , what exactly is the 3rd scenario to check if the new wallet is created for a new user with 1000 dinero?
