### ISSUE TITLE
Purge Cache for user specific Page

### ISSUE THREAD

**Issue by SagarBajpai** [Real-Dev-Squad/website-backend#292]
Right now `https://members.realdevsquad.com/${username}` page is served with Cloudflare. So it's cached copy is served every time. On changing, any user details it doesn't get reflected on the user page.

We needed an API that clears the cache at Cloudfare and we can see the updated Page.

We have created an endpoint `/cache/clear/self` that grabs a username from the cookies and clears the cache for the respective user.

**Comment by ankurnarkhede** [comment]
@SagarBajpai , what will be the behaviour of the route here and when will it get executed? When you say `GET /cache/clear/self`, that means the client will make a call for clearing the cache? 🤔

**Comment by SagarBajpai** [comment]
@ankurnarkhede User can clear the cache for his page from UI. User can trigger this UI whenever he wants but for a limited number times in a day. On triggering this API, the cache for his page will be purged, so the user can see his updated chanages.

**Comment by ankurnarkhede** [comment]
_But why should the user care about clearing the cache_? It would be a bad UX. 😬

I think if there's no way for us to configure it via Cloudflare, then from the application layer, we can purge the cache for a specific user when we update the user data or update their profile picture. We can handle this in the application and thus the changes would be reflected on the UI.

Opinion? @SagarBajpai , @ankushdharkar

**Comment by ankushdharkar** [comment]
@ankurnarkhede The members page contains the PRs and contributions, but has a 7 day cache. In case a member wants their contribution to appear earlier (say they want to show it to a recruiter as a recent task), in that case, we let the user clear just their details page on the members site

**Comment by ankurnarkhede** [comment]
@ankushdharkar , yeah, for the use case of PRs, we do not have a way to check if the resource has changed, as we aren't storing it. In this case, we can have a "Refresh" button on the UI of PR's and contributions which will handle this.

But for user details, can we handle it in the application later, as we know when the resource is getting updated?

**Comment by ankushdharkar** [comment]
A new recruiter may not know they want to click "refresh".  The first load of the page should be _fresh_.

Let the member control the page cache clearing of their page. Can discuss this more on the call.
