### ISSUE TITLE
Rename the `test-config` script to `validate-setup`

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-backend#303]
The term `test-config` can be confusing since it has nothing to do with the tests and it has do with validating the user's local setup.

https://github.com/Real-Dev-Squad/website-backend/blob/f025dd858a7d4b76a9a5c479bee434ef16ff9253/package.json#L10

**Comment by swarajpure** [comment]
Reserved for an internal member. Waiting for the member to reply here so the issue can be formally assigned to the concerned member.

**Comment by bhk31** [comment]
I will work on this.

**Comment by bhk31** [comment]
Closing the issue as it is merged.
