### ISSUE TITLE
[Dev Spec] Restrict user actions on backend

### ISSUE THREAD

**Issue by Cartmanishere** [Real-Dev-Squad/website-backend#323]
## Requirements
- We need a way to restrict a user's action on the backend.
- If it is a bad user, we will restrict the create/edit actions for the user.
- He/she will be able to view all the data but not be able to edit anything.

## Schema

In the `users` schema, we need to add a key/flag which where we can store whether the user is `restricted`.

There are two ways to go about this -- 

#### 1. Use the `roles` 
- We are planning to add `roles` key in the users schema which will define the user's permissions for e.g -- 
```
{
    roles: {
        member: true,
        admin: true
    }
}
```
- We make use of this `roles` map and add `restricted` as one of the roles. for e.g `restricted: true`. 

#### 2. Add a top-level field in the users schema -- 
- Add a key in the user schema which tells us whether the user is restricted -- 
```
{
    ...
    restricted: true
}
```
- [x]  Decide where we should store the flag in the users schema.

## Implementation
- Since this is application-wide validation, it makes sense to implement it as a middleware.
- We can only check for logged-in users, so this `limitAccess` middleware needs to come after the `authenticate` middleware.
- The devs working on adding new routes should not have to explicitly add this middleware while declaring the route middlewares.
- This middleware can be implicitly added after the `authenticate` middleware. So anytime `authenticate` is done, then this check is also performed. 
- Please check linked PR for what I mean by above.

RFC:
- @ankurnarkhede 
- @ankushdharkar 
- @whyDontI

**Comment by ankurnarkhede** [comment]
Yup, this makes sense. We can rely on this mechanism for authorization since we do not have to manage numerous entities and user groups.

The user's roles will be populated in the `authenticated` middleware and can be used further.
@Cartmanishere

**Comment by Cartmanishere** [comment]
@ankurnarkhede Ack. For this feature, I have decided that we can use the `roles` approach for where to store the `restricted` key. I will put a cleaned up PR for this.

Also for authorization, we can use the same `roles` key in User schema to add more authorization (for e.g for superuser, appOwners, etc). I can pick up that task after merging this.

**Comment by Cartmanishere** [comment]
- [ ] Need to update the `user` schema in the `website-data-models` to reflect the addition of field `roles`. cc: @rajakvk 

```
{
    ....
    roles: {
        restricted: true/false
    }
}
```
