### ISSUE TITLE
Update tasks/:username route to return active task.

### ISSUE THREAD

**Issue by bhk31** [Real-Dev-Squad/website-backend#368]
This API is needed for issue. https://github.com/Real-Dev-Squad/website-members/issues/146

**Comment by ankurnarkhede** [comment]
@bhk31 , do we have a different API to get inactive tasks?
What is the purpose of this API, can you describe it in description?

**Comment by bhk31** [comment]
> @bhk31 , do we have a different API to get inactive tasks?

@ankurnarkhede No we don't have any such API

>What is the purpose of this API, can you describe it in description?

Updated the description

**Comment by ankurnarkhede** [comment]
@bhk31 , yeah, but what about the inactive tasks?
In the user's profile, we will also need to show all the tasks, active as well as inactive, right?
The PR is currently just sending out active tasks. We can have any query param stating the filter required.

**Comment by bhk31** [comment]
> @bhk31 , yeah, but what about the inactive tasks?
> In the user's profile, we will also need to show all the tasks, active as well as inactive, right?
> The PR is currently just sending out active tasks. We can have any query param stating the filter required.

This has been requested by @sumitd94. Previously it was returning all task irrespective of the status.

Please check https://discord.com/channels/673083527624916993/735063616168001536/848896848706142248

**Comment by sumitd94** [comment]
@bhk31 Ideally the scenario should be, you will be getting a query param `?status=active`
Based on the status you have to return the tasks.

Make the API in such a way, if I pass `?status=inactive` it should return all the inactive tasks, and so on.

Change the API and make sure it does not break the system.
