### ISSUE TITLE
isNewUser is not getting set to true for new accounts

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#38]
When a user logins with Github for the first time, and has no record in the RDS, we create an entry with a randomized document id, but their Github display name, Github id (their username on Github) and Github token

There should have been a field `isNewUser: true` that denotes that this user has not yet selected their username/RDS_ID for the platform (this in turn should take them to a page where they can select)

Right now, for new users, the `isNewUser` field is not getting set. Please fix this.

![image](https://user-images.githubusercontent.com/1935403/93499566-c8278100-f930-11ea-8a69-e181535e9771.png)

**Comment by swarajpure** [comment]
PR merged. Closing this issue.
