### ISSUE TITLE
[RFC] TypeScript migration

### ISSUE THREAD

**Issue by ankurnarkhede** [Real-Dev-Squad/website-backend#414]
We need to migrate the project to typescript. This issue deals with finding a reliable way to migrate the project to typescript in an incremental way.

**Comment by ankur-lt** [comment]
Closing this issue as a duplicate of https://github.com/Real-Dev-Squad/website-backend/issues/453

**Comment by ankurnarkhede** [comment]
Closing this issue as a duplicate of #453
