### ISSUE TITLE
Add validation middlewares for challenges api endpoints

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-backend#428]
> First, update the [API Contracts](https://github.com/Real-Dev-Squad/website-api-contracts/blob/main/challenges/README.md) for the following changes. Once the API Contracts are approved start working on the requirements.  
# Requirements
- There are no request payload validations for [challenges POST APIs](https://github.com/Real-Dev-Squad/website-backend/blob/develop/routes/challenges.js), Add the validations.
- Change `/challenges/subscribe` to PATCH as the data is being updated and not created

**Comment by akshay1502** [comment]
@whyDontI I am working on [refactor PR](https://github.com/Real-Dev-Squad/website-backend/pull/271) in which I have added validator for [challenges POST api](https://github.com/Real-Dev-Squad/website-backend/pull/271/files#r726276267), so we only need to update /challenges/subscribe to PATCH.
