### ISSUE TITLE
[RFC] Migrate backend to TypeScript 

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-backend#453]
## Strategies to migrate the backend to TypeScript. 

** Below mention strategies are used by Airbnb.**

### Strategy 1: Change file by file. 
In this, we change files one by one from `.js` to `.ts` and add types/interfaces wherever needed. Here we enable allowJS option that allows and compiles both js and ts files error-free. But now the developer has to write code in both js and ts. we have to repeat until the full project is migrated 

### Strategy 2: All-in migration! (Airbnb used this)
In this strategy, they used code mods to convert the `.js` files to `.ts` in one go and We’ll need to add some any types and @ts-ignorecomments so the project compiles without errors.

Please refer to these links to learn more about the strategy :
https://medium.com/airbnb-engineering/ts-migrate-a-tool-for-migrating-to-typescript-at-scale-cd23bfeb5cc
https://www.youtube.com/watch?v=P-J9Eg7hJwE

Please comment if you know of any better strategies and improvements.

**Comment by swarajpure** [comment]
How about a third option, where you get the TS setup ready in the project but still allow js files to run as they were running earlier, now whatever next API is to be developed, that HAS to be written in TS?

Regarding the old API migration, we could literally assign 1 whole parent route to 1 developer and let that developer take care of the children routes and controllers, models, utils, tests etc related to those routes

**Comment by MehulKChaudhari** [comment]
> How about a third option, where you get the TS setup ready in the project but still allow js files to run as they were running earlier, now whatever next API is to be developed, that HAS to be written in TS?
> 
> Regarding the old API migration, we could literally assign 1 whole parent route to 1 developer and let that developer take care of the children routes and controllers, models, utils, tests etc related to those routes

Yeah also seems like a good strategy.

**Comment by ankushdharkar** [comment]
I am not a fan of strategy-2.

Strategy-1 seems reasonable, but we need some guidelines, especially for new developers to tackle JS-TS migrations.

**Comment by MehulKChaudhari** [comment]
> I am not a fan of strategy-2.
> 
> Strategy-1 seems reasonable, but we need some guidelines, especially for new developers to tackle JS-TS migrations.
> 
> If I change a file, do I also have to change all the dependent files to TS? And their dependent files?

No, not immediately, We can add the type of data used from `.js` dependent files in `.d.ts` then use types from here and later on create an issue ticket to change these files to `TS` as well.

**Comment by ivinayakg** [comment]
Hey, I want to work on this. 
Have worked with node ja and have some adequate experience with typescript. 
Let me know where I can help.

**Comment by MehulKChaudhari** [comment]
Closing this issue. We have decided to move with the **Strategy 1**
