### ISSUE TITLE
<Identity Service> Create /users/identityURLs API

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#462]
Create `/users/identityURLs` route which serves a GET request.

It will return all the identity URL objects by reading all the users object having identityURL.

**IdentityURL object: **
```
{
    username: ,
    identityURL: ,
    chainCode: ,
}
```

Refer to the other API in the backend for creating this one especially the members route.

For reference: [here](https://github.com/Real-Dev-Squad/identity-service/issues/18)

**Comment by pallabez** [comment]
I'd like to take up on this task.

**Comment by lakshayman** [comment]
great!
Assigned it to you

**Comment by lakshayman** [comment]
Dont need it now
