### ISSUE TITLE
[ New Task Workflow ] New Task workflow changes 

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-backend#464]
**Details :-**  https://github.com/Real-Dev-Squad/website-backend/issues/460

**Task :-**
Task status should be in the upper case
- [x] Update task status list in models and handle of side effects ( can be a sub issues)

**Comment by akshay1502** [comment]
I would like to work on this.

**Comment by Pavangbhat** [comment]
Assigned to @akshay1502
