### ISSUE TITLE
Generate chaincode

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#489]
What to do:
- [ ] Create a route /users/chaincode
- [ ] Authenticate the request coming to route
- [ ] Create a firestore model for chaincodes collection
- [ ] Controller for the above route will save the username and timestamp in firestore collection and gets the document ID.
- [ ] It should give the document ID as chaincode in response.

chaincodes Collection Object:
```
{
  id: <unique id>,
  username: <username>,
  timestamp: <timestamp>
}
```

Response:
```
{
    message: 'Generated New Chaincode!!',
    chaincode: <document id>
}
```

- [ ] Write the tests for it.

Refer This PR : https://github.com/Real-Dev-Squad/website-backend/pull/486

**Comment by shaksham08** [comment]
is this chaincode generated only once for the user? and if not then when exactly are we generating the chaincode?

**Comment by lakshayman** [comment]
@shaksham08 as of now, the user can generate it as many times as he/she wants but we are going to restrict it to 4 times a week and when the crypto site gets in action we will charge some dineros(virtual money) for every new chain code.

**Comment by shaksham08** [comment]
ok got it. also one thing when referring to a chaincode , is it something specific or just any random code ?

**Comment by samspecial** [comment]
Is the firestore related to Google Firebase?

**Comment by lakshayman** [comment]
@shaksham08 chain code is randomly generated code
@samspecial yes its google firestore

**Comment by samspecial** [comment]
@lakshayman ok

**Comment by samspecial** [comment]
> @shaksham08 chain code is randomly generated code @samspecial yes its google firestore

Ok

**Comment by ojas-elawadhi** [comment]
please assign me
