### ISSUE TITLE
Check current coverage and Files to ignore

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#501]
# Unit Testing
![image](https://user-images.githubusercontent.com/63191499/154795077-b312ea1e-45ae-4597-b6a4-151388329d7a.png)

## Files and Folders to ignore

- [ ] website-backend 
![image](https://user-images.githubusercontent.com/63191499/154795228-98bebb4e-ed48-464e-aefd-546e65378776.png)
- [ ] website-backend/config
![image](https://user-images.githubusercontent.com/63191499/154795257-35826bf0-f10b-46c4-baa2-fa5d8950d169.png)
- [ ] website-backend/constants
![image](https://user-images.githubusercontent.com/63191499/154795326-9d9cba5b-4ef0-443c-88e9-91e7d0b3c38d.png)
- [X] website-backend/controllers
![image](https://user-images.githubusercontent.com/63191499/154795363-9acf512f-ecb2-4020-9c5a-38c5e24b873c.png)
- [X] website-backend/docs
![image](https://user-images.githubusercontent.com/63191499/154795485-340ff6bd-59c4-40ae-9513-f5fa27bcf1aa.png)
- [ ] website-backend/middlewares
![image](https://user-images.githubusercontent.com/63191499/154795507-b855c9e4-52c6-4458-a1bf-6484c16e1482.png)
- [ ] website-backend/middlewares/validators
![image](https://user-images.githubusercontent.com/63191499/154795517-331754fc-b9d3-4489-a797-73be9c49351f.png)
- [X] website-backend/mockdata
![image](https://user-images.githubusercontent.com/63191499/154795560-01debaf9-aa5e-439b-bedd-a2ac54b23b7d.png)
- [ ] website-backend/models
![image](https://user-images.githubusercontent.com/63191499/154795663-856aab81-6b1d-4290-80fb-86196f51a04a.png)
- [ ] website-backend/routes
![image](https://user-images.githubusercontent.com/63191499/154795672-426486c8-5fee-4b7e-84fd-06d172088119.png)
- [ ] website-backend/scripts
![image](https://user-images.githubusercontent.com/63191499/154795689-f23313fa-43ff-4309-a4ed-cc1beee87304.png)
- [ ] website-backend/services
![image](https://user-images.githubusercontent.com/63191499/154795710-432a798b-4f1b-4996-ad39-1a9244332328.png)
- [ ] website-backend/utils
![image](https://user-images.githubusercontent.com/63191499/154795743-d24037fb-399a-41c0-9237-23f48ce4194e.png)

# Integration Testing
![image](https://user-images.githubusercontent.com/63191499/154795109-4692b362-57f3-46b6-b564-dc669bebbda7.png)

## Files and Folders to ignore
- [ ] website-backend 
![image](https://user-images.githubusercontent.com/63191499/154796561-a3f6e3d6-0526-40c6-ae02-6960ace44a5c.png)
- [ ] website-backend/config
![image](https://user-images.githubusercontent.com/63191499/154796568-6815a96c-9732-48d1-adca-22373f9cdec2.png)
- [ ] website-backend/constants
![image](https://user-images.githubusercontent.com/63191499/154796575-67a29e95-0487-4ca3-9c13-f25502d0331b.png)
- [ ] website-backend/controllers
![image](https://user-images.githubusercontent.com/63191499/154796586-35e999b8-7fd4-46b2-8d3f-9fd85d8178d4.png)
- [X] website-backend/docs
![image](https://user-images.githubusercontent.com/63191499/154796597-470cf04a-073e-4687-ac75-47fb8f941de1.png)
- [ ] website-backend/middlewares
![image](https://user-images.githubusercontent.com/63191499/154796609-cd572a19-44b6-4ce3-81bc-4054472ad8d7.png)
- [ ] website-backend/middlewares/validators
![image](https://user-images.githubusercontent.com/63191499/154796641-96209acb-ad9c-49fd-ab5f-ae4de02de5c1.png)
- [X] website-backend/mockdata
![image](https://user-images.githubusercontent.com/63191499/154796652-9cd9950f-efb1-4376-abf7-f839d6516dbb.png)
- [ ] website-backend/models
![image](https://user-images.githubusercontent.com/63191499/154796660-5c386878-17e0-41d6-ad64-2b72bd91af50.png)
- [ ] website-backend/routes
![image](https://user-images.githubusercontent.com/63191499/154796668-bbc1fc44-ba79-40fa-a6b9-6c6bd5cd2ef3.png)
- [ ] website-backend/scripts
![image](https://user-images.githubusercontent.com/63191499/154796681-9fb0ef32-96b1-445c-aa87-052f8b6acc3d.png)
- [ ] website-backend/services
![image](https://user-images.githubusercontent.com/63191499/154796695-56d582f7-a9ee-4ef9-9e43-802615b3b8c5.png)
- [ ] website-backend/utils
![image](https://user-images.githubusercontent.com/63191499/154796701-70425798-fd7a-4a91-bead-8115e6a4d221.png)

**Comment by ankur-lt** [comment]
For integration tests, ignore:
- docs/
- mockdata/
- public/

For unit tests, ignore:
- docs/
- mockdata/
- public/
