### ISSUE TITLE
Create /users/verify endpoint

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#504]
What to do:
- [ ] Create a route /users/verify.
- [ ] Route should be authenticated before calling the controller so that we know which user called the API. (Hint: See other endpoints)
- [ ] Controller should call the identity service /verify endpoint with the username and identityURL in the body.
- [ ] We just have to call the identity service endpoint and don't wait for the response if it's active. We are kind of queueing a request by calling that identity service endpoint.

**Comment by Deepansharora27** [comment]
Hi
I would like to work on this

**Comment by Deepansharora27** [comment]
Hi Lakshay, 
I am not clear with what do we mean by Identity Service Endpoint ?
Can you help me with this ?

**Comment by lakshayman** [comment]
Hi @Deepansharora27 
It is basically https://someurl.com/verify

**Comment by Deepansharora27** [comment]
@lakshayman 
May I also ask you that 
What purpose does this API Serve ?
Is is responsible for checking whether the current user is authenticated or not ?

**Comment by Deepansharora27** [comment]
@lakshayman Can you provide me the link to the Identity Service API ?
