### ISSUE TITLE
PATCH /users/:userId endpoint

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#520]
Sets the user's latest profileDiff approval key to `APPROVED`.

Merge the new data of the user from profileDiff collection into users collection

and log the changes in logs collection

Request you are getting
{
  'first_name': string,
  'last_name': string,
  'yoe': number,
  'company': string,
  'designation': string,
  'github_id': string,
  'linkedin_id': string,
  'twitter_id': string,
  'instagram_id': string,
  'website': string,
 }

For more info refer here: https://github.com/Real-Dev-Squad/identity-service/issues/18

**Comment by vikasosmium** [comment]
API Contract is not updated for this. @pallabez
