### ISSUE TITLE
Update {API}/tasks/self to return all the tasks assigned to a member

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-backend#527]
Currently, **{API}/tasks/self** endpoint returns a few sets of tasks based on some set of statutes.
Tasks:-
- [x] Endpoint should return all the tasks assigned to a member sorted by **startedOn** field the latest one should be in the top
- [x] Check if **/tasks/self** endpoint's handler function being used some where else

**Comment by Aryan-9211** [comment]
I want to work on this issue.
