### ISSUE TITLE
API Endpoints for Art Feature

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-backend#533]
We need to make three endpoints i.e. GET, GET all and POST for CSS Art Feature.
 
 Get - /arts/:artId
 Get all - /arts
 Post - /arts/add
 
Parameters which are required :
 - Username - (string)
 - Title - (string)
 - CSS - (string)
 - Price - (number)
 - Created At - (string)
 - Unique ID - (string)

**Comment by anmoldewanrai** [comment]
ETA - 24 Feb 2022
