### ISSUE TITLE
Improve test coverage to 50%

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-backend#539]
# Files that needs more test coverage
Priority in decreasing order

# Unit Test

## website-backend/models
- [x] badges.js 
- [x] stocks.js
- [x] members.js
- [x] challenges.js
- [x] auctions.js
- [x] tasks.js 
- [x] featureFlags.js  
- [x] wallets.js

![image](https://user-images.githubusercontent.com/63191499/155532055-ca340634-e008-484f-bbf3-463e49d4900d.png)

## website-backend/utils
![image](https://user-images.githubusercontent.com/63191499/155531845-2c72549d-49d7-496d-9c28-4218e6c7a81f.png)

## website-backend/services
![image](https://user-images.githubusercontent.com/63191499/155531893-23c96e81-f503-486b-9a54-a58a79dc8db8.png)

# Integration Test

Already Covered

**Comment by pallabez** [comment]
Working on website-backend/models/auctions.js

**Comment by pallabez** [comment]
Working on `website-backend/models/wallets.js`

**Comment by siddhesh494** [comment]
Working on `website-backend/models/members.js`

**Comment by siddhesh494** [comment]
Working on `website-backend/models/badges.js`
