### ISSUE TITLE
POST /flag/add endpoint

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-backend#564]
# POST /flag/add 

## Parent Issue
- #563 

## Steps

Branch - `feature-flag/add`
- [x] Create flag.js file for route, controller and models
- [x] Set `/flag/add` authentication to `super_user` and add `/flag` route to `routes/index.js`
- [x] Create controller and model (function name - `addFlag` for both)

Example of object to be added 
```
title: dark-mode
enabled: true/flase
roles: [members, no_role, super_user],
users: {
  "pallab id": true,
  "rohit id": false,
},
```

-----

Branch - `feature-flag/add-tests-validator`
- [x] Write integration and unit test 
- [x] Add `joi` validation middle ware (All the fields are required/not optional)

**Comment by RahulGoyal-tech** [comment]
Assign me this issue please!!

**Comment by shubham-y** [comment]
Reopening the issue as PR is in progress

**Comment by pallabez** [comment]
Now Handled in the repo 
- https://github.com/Real-Dev-Squad/feature-flag-service
