### ISSUE TITLE
Remove swagger docs 

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-backend#602]
## Why? 
- [API contracts](https://github.com/Real-Dev-Squad/website-api-contracts) serves the same purpose.

## Remove swagger docs comments from all route files (Assigned to Rajat)
- Remove the comments
Eg - [Click here](https://github.com/Real-Dev-Squad/website-backend/blob/cc9476dec38137093f7108bcd2566b4bb5b99053/routes/auth.js#L5-L34)

## Remove `/api-docs`  (Assigned To Poonam)
- https://github.com/Real-Dev-Squad/website-backend/blob/develop/middlewares/index.js#L51-L58
- Remove swagger package https://github.com/Real-Dev-Squad/website-backend/blob/cc9476dec38137093f7108bcd2566b4bb5b99053/package.json#L38-L39

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue.

**Comment by rajat-mehra05** [comment]
I'll pick this issue up to know more about backend.

**Comment by poonammohata** [comment]
hey @pallabez, i would like to work on this.

**Comment by poonammohata** [comment]
@pallabez i would like to work on Remove /api-docs task
