### ISSUE TITLE
Deprecate `/feature-flag` API

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-backend#605]
Things to remove of featureFlag -
- [ ] Routes
- [ ] Controllers
- [ ] Models
- [ ] Integration tests
- [ ] Unit tests
- [ ] Validators
- [ ] `/feature-flag route` from `routes/index.js`

**Comment by poonammohata** [comment]
hey @pallabez , i would like to take this issue

**Comment by pallabez** [comment]
Assigned it to you @poonammohata

**Comment by poonammohata** [comment]
hey @pallabez , in swaggerDefinition and apiSchema files also, there is something defined related to feature-flag, do i have to remove that also?

**Comment by pallabez** [comment]
Hey @poonammohata, Can you share the link of which part of code you are talking about?

**Comment by poonammohata** [comment]
@pallabez  it is in --
1. https://github.com/Real-Dev-Squad/website-backend/blob/develop/docs/swaggerDefinition.js
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/54801934/168472401-b00a9494-ebb5-4c05-9dd7-6fa171bd440f.png">
2. https://github.com/Real-Dev-Squad/website-backend/blob/develop/public/apiSchema.json
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/54801934/168472465-90b4780f-f817-48e5-b45f-482fc8e39037.png">

**Comment by pallabez** [comment]
Not needed as https://github.com/Real-Dev-Squad/website-backend/issues/602 is handling that. Thank you for bringing that to attention.
