### ISSUE TITLE
Deprecate `/members` API

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-backend#608]
Deprecating the [/members](https://api.realdevsquad.com/members) endpoint as the same purpose is served by the [/users](https://api.realdevsquad.com/users) endpoint. 

Changes needed related to `/members` endpoint-
- [ ] Remove GET `/members` from members route
- [ ] Remove `getMembers` function from members controller
- [ ] Remove `fetchUsers` function from members model
- [ ] Remove Integration tests for `/members`
- [ ] Remove API contract for `/members`
- [ ] Update `/users` endpoint with a filter to return users with `role : { members: true }`

Please feel free to add more points if more changes are required

Post Merging changes:

- Update [config](https://github.com/Real-Dev-Squad/website-backend/blob/912c397f8f229893f789477f39be99051ac17632/config/default.js#L77-L79) to replace `/members` with `/users` for caching

**Comment by aakankshadhurandhar** [comment]
@shubham-y  Can you assign me this issue ?

**Comment by shubham-y** [comment]
> @shubham-y Can you assign me this issue ?

Done! Assigned it to you. Please do let me know the ETA

**Comment by pallabez** [comment]
Aren't we using `fetcheUsers` model function in a lot of places?

**Comment by aakankshadhurandhar** [comment]
> > @shubham-y Can you assign me this issue ?
> 
> Done! Assigned it to you. Please do let me know the ETA

ETA 24th May

**Comment by shubham-y** [comment]
> Aren't we using `fetcheUsers` model function in a lot of places?
> 
> Also, why are we removing GET `/users`? Shouldn't we try to migrate GET `/members` functionality to GET `/users` and remove GET `/members` instead?
> 
> Reason: `/members` is giving us non member details which kind of doesn't make sense.

Yes, it makes sense. Updated the issue details

**Comment by RitikJaiswal75** [comment]
closing in lieu of: https://github.com/Real-Dev-Squad/website-members/issues/547
