### ISSUE TITLE
Migrate usage of `/members` to `/users`

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-backend#610]
Reason - Currently, both [/members](https://api.realdevsquad.com/members) & [/users](https://api.realdevsquad.com/users) return all users data. So, it is better to have a single endpoint to return all users and more intuitive to have `/users` return it.

The sequence of events to be followed:

- Verify and make the response of [users](https://api.realdevsquad.com/users) endpoint similar to [members](https://api.realdevsquad.com/members) endpoint
- Update the API contract of [users](https://api.realdevsquad.com/users) endpoint if there are any changes
- Create PRs in all frontend apps where [members](https://api.realdevsquad.com/members) endpoint is in use and update it to [users](https://api.realdevsquad.com/users) endpoint
- Merge the backend and frontend PRs in respective staging environments.
- Verify everything is working fine in staging environment.
- Once verified, push the backend and frontend changes to the production environment respectively
- Monitor New Relic logs for a week to verify if [members](https://api.realdevsquad.com/members) endpoint is still in use or not
- Simultaneously work on deprecating [members](https://api.realdevsquad.com/members) endpoint.
- After monitoring, deprecate the [members](https://api.realdevsquad.com/members) endpoint permanently.
- Update the API contract of users to add a filter 

Issues:

- [ ] Update `/users` API
- [ ] _List of issues in frontend apps to be updated_
- [x] #608

**Comment by RitikJaiswal75** [comment]
closing in lieu of: https://github.com/Real-Dev-Squad/website-members/issues/547
