### ISSUE TITLE
Create a function to obfuscate phone and email of the user

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#620]
ProfileDiff.js Controller
![1](https://user-images.githubusercontent.com/45519620/173135108-e543c652-4bfa-4e5a-86b5-2577742c9143.PNG)

User.js Controller
![2](https://user-images.githubusercontent.com/45519620/173135114-8edb004e-ad05-42de-88bc-8f89377b8a62.PNG)

Create a function for these 4 lines as they are doing the same thing.

**Comment by RahulGoyal-tech** [comment]
Assigning this issue to myself.
