### ISSUE TITLE
[Suggestion] Removing user data fetching at authentication middleware

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-backend#629]
We can pass `userId` & `roles` in the JWT. If the user data is needed then we can fetch it in controller or maybe a different middleware. 

https://github.com/Real-Dev-Squad/website-backend/blob/6dd78c1245086fa1dcd3f64ee46d64cc58d535f6/middlewares/authenticate.js#L82

**Comment by pallabez** [comment]
Discussed with Ankush. Roles in JWT is a overhead to maintain.

**Comment by ivinayakg** [comment]
So how are we moving forward for this. 
Are we keeping as it is or going to change to store only roles and userid in the jwt token

**Comment by pallabez** [comment]
On discussion we concluded that those details shouldn't be stored in JWT.
We are going with -
- Removing userId from JWT
- Adding caching layer to backend (perhaps redis)
