### ISSUE TITLE
Refactor Roles List constant and export it

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#633]
Export object at [this location](https://github.com/Real-Dev-Squad/website-backend/blob/18aa66dd9331dc2e1b44feb3073608ed502bc12d/middlewares/authorization.js#L8-L12) as just `ROLES_LIST`, so that it can be used in code as `ROLES_LIST.SUPER_USER`

(e.g  [here](https://github.com/Real-Dev-Squad/website-backend/blob/ccc712575ba3dfb7e35a0f9fb92659d2fcbccce1/routes/tasks.js#L101-L102) we can then change it to  `authorizeUser(ROLES_LIST.SUPER_USER)`, and prevent issues arising due to typos like "super-user", or "superUser", or "super_user". In ideal world, we will soon have TypeScript!)

**Comment by pallabez** [comment]
Issue has been resolved on 
- https://github.com/Real-Dev-Squad/website-backend/issues/582
