### ISSUE TITLE
Get users based on status

### ISSUE THREAD

**Issue by SanthoshBalagur** [Real-Dev-Squad/website-backend#635]
### The Requirement:
- Get users based on status
- Enhance [GET] `/users` endpoint

### For example:
- `/users?status=idle` will return an idle users
-  `/users?status=idle&members=true` return only members who are idle

**Comment by SanketDhabarde** [comment]
Please assign it to me. I will work on it.

**Comment by SanketDhabarde** [comment]
The outcome of this task was to get idle users/members. Closing this issue as this requirement will be taken care of at https://github.com/Real-Dev-Squad/website-status/issues/336
