### ISSUE TITLE
Secure task api 

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-backend#673]
Currently, task API is open. Make it secure, only accessible by the superuser

**Comment by shmbajaj** [comment]
@prakashchoudhary07 I want to work on this issue, c
an you describe which routes to prootect as some are already secure.

**Comment by prakashchoudhary07** [comment]
Closing this issue, as it has been already taken care of here https://github.com/Real-Dev-Squad/website-backend/blob/339e0c101debc3a707aa277363132c02ac7969ae/routes/tasks.js#L13-L15
