### ISSUE TITLE
Change the status key value pair in the api.rds.com/users/:userName response

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#742]
As of now when the user is `OOO` the `status` in the response is either active or `OOO` but we would need to change this for the user management service, the response should look something as follows : 

### When OOO
```
{
  "status": {
    "ooo": "true",
    "return_date": "20.10.2022",
    "reason": "health issues",
    "monthly_hours_availability": ""
  }
}
```
### When not OOO

```
{
  "status": {
    "ooo": "false",
    "monthly_hours_availability": "80",
    "return_date": "",
    "reason": ""
  }
}
```

**Comment by BALAJI141031** [comment]
bro ready to take this issue but want some more context so can we connect in your free time

**Comment by heyrandhir** [comment]
> bro ready to take this issue but want some more context so can we connect in your free time

Hi Balaji. I have been asked to complete this task myself. Will let you know in case I need any other API for User Management. Thanks.

**Comment by heyrandhir** [comment]
Closing this as we are making a new collection instead of modifying the existing document. In the existing User collection need to make some changes. Ticket for the same https://github.com/Real-Dev-Squad/website-backend/issues/789 .
