### ISSUE TITLE
Add an endpoint to save idle users form data

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-backend#753]
## Issue
Create endpoints to save and extract the idle user's form data.

### Description
Create an endpoint that can save the data that is being sent from my site's idle users form
Link to the issue ticket: https://github.com/Real-Dev-Squad/website-my/issues/293

Create another endpoint that can extract the user data from the database to access it in the status site.
Link to the issue ticket: https://github.com/Real-Dev-Squad/website-status/issues/337

The big picture is to manage all the idle users effectively
Link to the issue ticket: https://github.com/Real-Dev-Squad/todo-action-items/issues/107

Discuss the collection to be used whether to create a new collection or use any pre-existing collection
find out ways to show data in case a different collection is used, and how will the data be shown for the correct user.

**Comment by shmbajaj** [comment]
@RitikJaiswal75 I want to work on this issue.

**Comment by shmbajaj** [comment]
# Status Update

1. [12/12/2022] No Work Done

**Comment by RitikJaiswal75** [comment]
Hi @shmbajaj the issue has already been solved by @heyrandhir
