### ISSUE TITLE
CORS Error on the website

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-backend#756]
### Issue:

On https://realdevsquad.com/ , there is a CORS error because of an incorrect regex in the allowed origin in configuration files. The error isn't present on the subdomains

![image](https://user-images.githubusercontent.com/42349041/197848735-e114cd43-9904-4c90-b975-c2154f33b176.png)

### Solution:
Correct the regex which makes sure that `.` is optional, anything before it and after `https://` is acceptable

**Comment by ankushdharkar** [comment]
Fixed in #762
