### ISSUE TITLE
Add query param for searching users whose name contains a certain prefix term in the `/users` endpoint

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#841]
As of now, the endpoint /users/:user-name returns a specific user if it's found in the collection and not found if it doesn't exist. However, we would also need to get all users whose names match the particular prefix someone is querying for. this can be done via adding a query param in the /users endpoint.

**Comment by Muralidhar22** [comment]
please assign this to me

**Comment by heyrandhir** [comment]
Done. Let me know the ETA.
