### ISSUE TITLE
Add a max size in the `/users` query param `size`

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#842]
the query param `size` should have an upper limit on the no of users requested from the `/users` endpoint

**Comment by heyrandhir** [comment]
Hi @shmbajaj you are right this issue deals with pagination. Pagination is already implemented for `/users`. However, there is a query parameter `size` which currently has no upper cap. Someone can pass `/users?size=10000` which will end up consuming all our firebase reads. Hence we need an upper cap on the size param which can be requested. Hope I was able to make it clear.

**Comment by shmbajaj** [comment]
@heyrandhir can you assign this to me....

**Comment by heyrandhir** [comment]
> @heyrandhir can you assign this to me....

Done

**Comment by shmbajaj** [comment]
[PR: Max size for size query param](https://github.com/Real-Dev-Squad/website-backend/pull/873)
