### ISSUE TITLE
Join Section | multiple data creation

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-backend#850]
Every time the User sends in to submit a request a new document is created. 
We are sending a PUT request every time the user sends the data from the front end.

Solution:
We need to check if the data for userId is already present or not.
If already present fail the request saying data already present unless the profile is rejected by the superuser and the user is asked to re-fill the join data.

**Comment by satyam73** [comment]
Hello @RitikJaiswal75 I want to work on this issue.

**Comment by RitikJaiswal75** [comment]
Hello @satyam73 how is the work going on this? any blockers?

**Comment by satyam73** [comment]
> Hello @satyam73 how is the work going on this? any blockers?

Can I have more context for this?

**Comment by RitikJaiswal75** [comment]
please link your solution branch here

**Comment by satyam73** [comment]
> Contributor
Did you mean PR?

**Comment by satyam73** [comment]
> Contributor
Did you mean PR?
