### ISSUE TITLE
Refactor the user-status endpoint

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#857]
Modify the following points in user-status endpoint.
- [ ] Add new route `/self` for GET and PATCH
- [ ] Change route name from `/user-status` to `/users/status`
- [ ] Update tests for the new routes
- [ ] Change the collection name from `userStatus` to `usersStatus`

**Comment by Manas-E** [comment]
Is it open I want to work on this?
@heyrandhir

**Comment by heyrandhir** [comment]
Hi @Manas-E PR is already raised by me for this one. Sorry, I should have assigned this to myself. I had missed that.
