### ISSUE TITLE
Necessary Firestore indices in userStatus collection

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-backend#868]
Following indices creation is needed for the sort idle user feature 

### Collection Id:
usersStatus

## Fields to be indexed:
currentStatus.state Ascending
currentStatus.from Ascending

**Comment by ankushdharkar** [comment]
Added this index.

Set the Query Scope as "Collection"

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1935403/206927644-5c7f0b34-88a1-4d41-a117-c1b47ab5cf1f.png">
