### ISSUE TITLE
Handling batch writes for more than 500 operations

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#890]
To perform updates on multiple documents Firestore provides us with the batch transaction.  Once the batch is created it can be committed hence completing the updates in one go. However, a limitation to this is we can batch a maximum of 500 operations in Cloud Firestore. 

If you try to add more than 500 operations it would lead to a failed transaction. A failed transaction returns an error and does not write anything to the database. You do not need to roll back the transaction. Cloud Firestore does this automatically. [read more](https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes)

We can catch this error using a try-catch block as shown [here](https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes) and if it throws an error we can log it in our logger as well and show it in the API response as well.

To perform more than 500 operations we can do so using multiple batches by creating some sort of batched array as suggested here in this StackOverflow [link](https://stackoverflow.com/questions/52165352/how-can-i-update-more-than-500-docs-in-firestore-using-batch)

**Comment by shmbajaj** [comment]
Hey @heyrandhir if you haven't started this, then please assign this to me.

**Comment by heyrandhir** [comment]
Hi @shmbajaj I had created this issue when I had discovered about batch writes having a limitation of 500 users. In my module of user-management I have handled this. You can check if there are any other modules which are using batch writes and have not handled the case of > 500 docs update you can create an issue and work on that.
