### ISSUE TITLE
`users` api pagination enhancement

### ISSUE THREAD

**Issue by Muralidhar22** [Real-Dev-Squad/website-backend#899]
## why this change
https://firebeast.dev/tips/do-not-use-offset

Our code: [fetchUsers function in user model](https://github.com/Real-Dev-Squad/website-backend/blob/a5f0ff850cc862824a87c833f61d77b489cfdf1d/models/users.js#L135)
## ~~Approach 1~~
- For client to receive next batch of results with `size` param, it should pass the last `id` in the current resulted batch/list as `query param`.
- For client to receive previous batch of results with `size` param, it should pass the first `id` in the current resulted batch/list as `query param`.
### example:
```
REQUEST: 
             https://api.realdevsquad.com/users?next=<id>&size=(0<n<=100)
             https://api.realdevsquad.com/users?prev=<id>&size=(0<n<=100)
```
```javascript
RESPONSE:
           {
              message: <string>,
              users: <list>
           }
```

## Approach 2 (Implemented)

- when `users` endpoint is hit with a request the response would be.
### example:
```
REQUEST: 
             https://api.realdevsquad.com/users?next=<id>&size=(0<n<=100)
             https://api.realdevsquad.com/users?prev=<id>&size=(0<n<=100)
```
```javascript
RESPONSE:
           {
              message: <string>,
              users: <list>,
              nextPage: <id: string>,
              previousPage: <id: string> (if previous batch exists)
           }
```

- If client needs next batch of results the need to send `nextPage` value and if needed previous batch results has to send `previousPage` value from the `response` as `query param`.

### Saving document id in a cookie
- Setting a `HTTP only cookie` having values stored as
```javascript
COOKIE:
              {
               [previous page number]: `id` of the first document in the current resulted batch.
               [current page number]: `id` of the first document in the current resulted batch.
               [next page number]: `id` of the last document in the current resulted batch.
              }
```
```
REQUEST: 
             https://api.realdevsquad.com/users?page=<number>&size=(0<n<=100)
```
```javascript
RESPONSE:
           {
              message: <string>,
              users: <list>
           }
```
- Based upon `page` param received `previous page number`,  `current page number` , `next page number` is set.
- previous page results are fetched by using [limitToLast](https://firebase.google.com/docs/reference/node/firebase.firestore.Query.html#limittolast) method.
- current page results can be fetched by using [startAt](https://firebase.google.com/docs/reference/node/firebase.firestore.Query.html#startat) method.
- next page results can be fetched by using [startAfter](https://firebase.google.com/docs/reference/node/firebase.firestore.Query.html#startafter) method.

## common points for all approaches. 
**Limitation**: Can't be fetched any arbitrary page results, has to be fetched either in forward or backward direction consequently.
- Depending upon the page size (default and max: `100`) the id of the document used to navigate previous/next page is produced .

**Comment by harshith-venkatesh** [comment]
Could you write more points on approach 2
It is a standard practice which I have observed in my current and prev company.
What is the page size we would be looking for and does previous page and next page Id is generated independent of page size?

**Comment by harshith-venkatesh** [comment]
https://firebase.google.com/docs/firestore/query-data/query-cursors#paginate_a_query
Suggestions and links to PR by @RitikJaiswal75 seems to help these approaches with implemented examples

**Comment by heyrandhir** [comment]
The limitation of all the 3 approaches that I am able to understand is we wont be able to query documents at arbitrary indexes such as documents from index 200 to 300. we have to always traverse it in sequential order. so that we know what was the document id of last document so we can request the next batch. Am I right @Muralidhar22

**Comment by Muralidhar22** [comment]
> Could you write more points on approach 2 It is a standard practice which I have observed in my current and prev company. What is the page size we would be looking for and does previous page and next page Id is generated independent of page size?

Hi @harshith-venkatesh will mention

**Comment by prakashchoudhary07** [comment]
At what point will we be needing the previous page? Do we have any use cases for it?

I prefer Approach 1 or 2  over 3 (based on the previous page requirements)

Maintaining cookies for nextId, Just adds up in complexity I feel,
In its case, a link cannot be shared for resources between 50-75, As the Ids are maintained in a cookie, But in approaches 1 and 2 it is possible as the ids are included in the URL itself

**Comment by Muralidhar22** [comment]
> At what point will we be needing the previous page? Do we have any use cases for it?
> `comment: Unless the previous page values are not cached on frontend there's no use case I think.`
> I prefer Approach 1 or 2 over 3 (based on the previous page requirements)
> 
> Maintaining cookies for nextId, Just adds up in complexity I feel, In its case, a link cannot be shared for resources between 50-75, As the Ids are maintained in a cookie, But in approaches 1 and 2 it is possible as the ids are included in the URL itself

 Yes I think shareable link is possible only possible in approaches 1 and 2.
