### ISSUE TITLE
Fix failing tests - `/users?search`

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-backend#913]
## Issue
- Integration tests are failing on develop and new pull requests for `/users?search` route 
https://github.com/Real-Dev-Squad/website-backend/actions/runs/4050293839/jobs/6967550570

## Steps to Reproduce
- Take the latest pull from develop
- Run `yarn test` or `yarn test-integration`

**Comment by Muralidhar22** [comment]
Root cause: https://github.com/Real-Dev-Squad/website-backend/pull/832#pullrequestreview-1274595239
Rohan raj will fix this with pagination PR, as validation needs to be updated in that as well
ref: https://github.com/Real-Dev-Squad/website-backend/pull/898

**Comment by rohan09-raj** [comment]
Thanks for the reference issues. Should we close this issue ?

**Comment by shmbajaj** [comment]
> 

I believe something misunderstanding, is here [#832 (review)](https://github.com/Real-Dev-Squad/website-backend/pull/832#pullrequestreview-1274595239) is not cause for this.
