### ISSUE TITLE
Add environment variable on `staging` backend

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-backend#927]
## Action Items
- Create a environment key for the staging backend
- The key structure in config is following
```
botToken: {
    botPublicKey: "BOT_PUBLIC_KEY",
},
```
**Public Key**
https://github.com/Real-Dev-Squad/website-backend/blob/823fb926c71dbb87c2b3a6b44ea13b3cc25af26e/config/test.js#L66

**Comment by prakashchoudhary07** [comment]
How does this work? I thought public and private keys are generated together.

By the way, I have added the env key 'BOT_PUBLIC_KEY' and the value from the test config file.
