### ISSUE TITLE
Feature request: GET api call to send unique token to my site 

### ISSUE THREAD

**Issue by shreya-mishra** [Real-Dev-Squad/website-backend#940]
We're implementing Sign in with QR code feature in mobile app.

For more information you can check https://github.com/Real-Dev-Squad/mobile-app/issues/146 this out

Feel free to tag me  in mobile-app channel, if you want any further clarifications.

**Comment by ruthv1k** [comment]
I'm interested in working on this

**Comment by Satyam005** [comment]
Hello @shreya-mishra, I would like to take this up
