### ISSUE TITLE
Feature Request: POST Request to create a qr-code-auth document

### ISSUE THREAD

**Issue by shreya-mishra** [Real-Dev-Squad/website-backend#941]
It is used while scanning the QR code from the mobile app on my-site QR code.

**Request**
POST

**Endpoint**
 /auth/qr-code-auth
 
 **Request Body**
```
 {
  "device_info": "t5k77PHnuDSrgEzvMJAj",
  "user_id": "NLFSj7Kz30oHgolfIZtJ",
  "device_id": "sdkdjASdjdsfns3kdj"
}

```
**Request Response**
Status: 201
Content-Type: application/json

```
{
  "data": {
    "user_id": "SooJK37gzjIZfFNH0tlL",
    "device_info": "t5k77PHnuDSrgEzvMJAj",
    "device_id": "sdkdjASdjdsfns3kdj",
    "authorization_status": "NOT_INIT"
  },
  "message": "Authentication document created successfully."
}
```
In case of any doubt let's have a discussion on a call or you can text @mobile-app-react-native channel.
You can also check our[ API contract](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/qr-code-auth
) in case of error responses.

**Comment by Satyam005** [comment]
Hi @shreya-mishra, I will take this up...

**Comment by shreya-mishra** [comment]
What will be the ETA .

**Comment by isVivek99** [comment]
we will be following this api contract moving forward [url](https://github.com/Real-Dev-Squad/website-api-contracts/pull/134/files)

**Comment by shreya-mishra** [comment]
@isVivek99 please mention the ETA of the ticket

**Comment by isVivek99** [comment]
my current `ETA` would be `27th June`
