### ISSUE TITLE
[RFC] GitHub Duplication

### ISSUE THREAD

**Issue by iamYashSinha** [Real-Dev-Squad/website-backend#957]
**Issue** - #929 

**Possible solutions**

1. Backend-solution: fetch github_id from the API and store it to the new variable called github_user_id;

2. What if we make a separate page for individuals who have recently changed their github_userName and require them to visit it in order to merge their document (old+new)? We can update the user's document using their previous github_userName and new github_newUserName.

 **Problems with the solutions**

1. problem with 1st solution - the variable called github_id which is actually storing the github_Username, the dependencies are everywhere, hence it is difficult to change that variable from github_id to github_username, I think for now we should stick to the temporary plan like creating another variable and fetch the github_id from the github_api.

2. problem with 2nd solution - How will people know that they have multiple documents in the RDS database, secondly, it is a manual process in which people must visit the website and provide information such as old GitHub username and new username.

3. When comparing these two potential solutions, the first is a type of automated service, while the second is manual.

**Note:** 
1. I've included all possible dependencies of "github_id" from all repositories. 

2. Please refer to the doc and give your valuable comments 

3. doc link - https://docs.google.com/document/d/1w5hYUaJgFG71d8GgzcTxA3irkiTzFX6YtLtAuBHEi7I/edit

4. Requesting other devs to give your comments on this @ankushdharkar  @RitikJaiswal75 @prakashchoudhary07 @satyam73 @pallabez @TanishqSingla

**Comment by iamYashSinha** [comment]
### Important! 
1. Apart from that, there is one more parameter that is unchangeable by changing the github_username and as we know,  we must have to find relevant parameters that are relevant to both documents in order to update the document.
2. ![Screenshot from 2023-03-16 21-34-35](https://user-images.githubusercontent.com/71075101/225681348-a60dc2ad-5635-4f19-bc7a-6ce301dc8011.png)

### Solution: 
1. a parameter called **node_id** which remains constant on changing the github_username, I've verified this as well. 

2. The **node_id** is different from the **id** property, which is also a **unique identifier** for GitHub objects, but it is an integer and is not guaranteed to be unique across different types of objects.

3. The **node_id is designed to be a stable** and **secure identifier** that can be **used to access** an object's data via the GraphQL API, and it **remains consistent** even if the object's other properties, such as its name or description, are changed.

**Comment by satyam73** [comment]
![image](https://user-images.githubusercontent.com/85296770/225791049-65302a4b-e564-4176-830b-62cd23981faf.png)
It is already mentioned here that it is not unique across all the different types of object. Then how we will use this?

**Comment by prakashchoudhary07** [comment]
> ![image](https://user-images.githubusercontent.com/85296770/225791049-65302a4b-e564-4176-830b-62cd23981faf.png) It is already mentioned here that it is not unique across all the different types of object. Then how we will use this?

+1

**Comment by prakashchoudhary07** [comment]
Why are we not using `id` here?

**Comment by prakashchoudhary07** [comment]
And after changing the GitHub username, let's say we are storing some GitHub unique key, How will we know that we have to update the user details from GitHub to be re-fetched in RDS so that we are in sync with GitHub details?
At what point will we do this?

**Comment by prakashchoudhary07** [comment]
By the where do we use the GitHub username in RDS?

**Comment by iamYashSinha** [comment]
Answering the 1st question - Node IDs are used in the GitHub API to specify a specific resource when making requests. For example, if you wanted to retrieve information about a specific repository, you could use the repository's node_id in your API request to retrieve the relevant data. It's important to note that the node_id is not the same as the repository's id or other identifiers used by GitHub hence We can't use this on the other hand we have "github_id"  to know more I've already created a document on this [click here](https://docs.google.com/document/d/1w5hYUaJgFG71d8GgzcTxA3irkiTzFX6YtLtAuBHEi7I/edit)

Answering the 2nd question- for that, I've already suggested a possible solution like GitHub API providing the "github_id" which is unchangeable or remains constant even after changing the GitHub username, so when a user comes to the RDS website he/she has to register again, afterward a new or duplicated document is created in the RDS with the help of github_id parameter provided by Github API we can then update the user. 

Answering the 3rd question- We can use it by creating another field in the database so that we can store the user's "gtihub_id".

Sorry for the late comment I was OOO till the 10th of April.

**Comment by prakashchoudhary07** [comment]
Closing this, as it has been completed
