### ISSUE TITLE
Refactor: Use constants for error messages

### ISSUE THREAD

**Issue by TanishqSingla** [Real-Dev-Squad/website-backend#963]
## Overview
There are numerous examples of hard-coded messages such as `An internal server error occured` in the controllers. Change them to use relevant constants that are already defined.

**Comment by VladJav** [comment]
Can you assigned me to this issue?

**Comment by TanishqSingla** [comment]
> Can you assigned me to this issue?

@VladJav I apologise for the late response, please do not wait for being assigned to the task, create your PR and mention it in the comments here.
