### ISSUE TITLE
Integration tests for sorting and filtering users. 

### ISSUE THREAD

**Issue by yesyash** [Real-Dev-Squad/website-backend#987]
Write integration test for #946 

TODO's
- [ ] fetchOpenPRs
- [ ] fetchMergedPRs
- [ ] fetchOpenIssues
- [ ] fetchClosedIssues
- [ ] fetchMultiplePageResults
- [ ] getFilteredPRsOrIssues
- [ ] fetchAllUsers
- [ ] getUsers

**Comment by Srinja333** [comment]
I don't know how to write tests, but can I try this? Because it will help me to gain my knowledge.

**Comment by khalatevarun** [comment]
Will pick this up @yesyash

**Comment by yesyash** [comment]
> I don't know how to write tests, but can I try this? Because it will help me to gain my knowledge.

Hi, @Srinja333 thank you for asking but this ticket is currently tightly coupled with the pr mentioned & @khalatevarun has started working on this already. 

Would you like this to take up this pr #980 it's an interesting one.
